In [1]:
import os
import sys
from pathlib import Path

ROOT = Path(os.path.abspath('')).resolve().parents[2]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))


import nvitk as nv
from nvitk import db
import pandas as pd

Build DB

In [2]:
from nvitk.db import DataRepo, import_pesabrain_source, list_pesabrain_sources

db_base = Path("/data_local/LabVF/PESA-Brain/DB/DB")
repo = DataRepo("~/nvitk/dataset", auto_scaffold=True)

In [3]:
# res = import_pesabrain_source(
#     repo,
#     db_base,
#     "PESABrain_All_IDs.xlsx",
#     sheet="Sheet1",
#     source_kind="subject_ids",
# )

# res = import_pesabrain_source(
#     repo,
#     db_base,
#     "PESABrain_All_4DFlow_IDs.xlsx",
#     sheet="Sheet1",
#     source_kind="subject_ids",
# )

# import_pesabrain_source(
#     repo,
#     db_base,
#     "PESABrain_SubjectCatalog_AllXNAT_20260216.xlsx",
#     sheet="Datos",
#     source_kind="subject_catalog",
# )

# import_pesabrain_source(
#     repo,
#     db_base,
#     "PESABrain_Clinical_20260216.xlsx",
#     sheet="Sheet1",
#     source_kind="clinical_wide",
# )

# import_pesabrain_source(repo, db_base, "PESABrain_APOE_20260318.xlsx", sheet="Sheet1", source_kind="clinical_wide")
# import_pesabrain_source(repo, db_base, "PESABrain_TAC_20260318.xlsx", sheet="Sheet1", source_kind="clinical_wide")
# import_pesabrain_source(repo, db_base, "PESABrain_Echography_CarotidePlaque_20260216.xlsx", sheet="Sheet1", source_kind="clinical_wide")

# import_pesabrain_source(repo, db_base, "PESABrain_4DFlow_LocalizedPI_20260216.xlsx", sheet="PESABrain_AnalysisDB_Batch1", source_kind="image_wide")
# import_pesabrain_source(repo, db_base, "PESABrain_4DFlow_LocalizedTimeAvgFlow_20260216.xlsx", sheet="PESABrain_AnalysisDB_Batch1", source_kind="image_wide")

# import_pesabrain_source(repo, db_base, "PESABrain_4DFlow_LocalizedTimeseriesFlow_Wide_20260216.xlsx", sheet="Datos", source_kind="image_timeseries_wide")

# import_pesabrain_source(repo, db_base, "PESABrain_ASLPerfusion_ThrMeanCBF_20260216.xlsx", sheet="Sheet1", source_kind="image_wide")
# import_pesabrain_source(repo, db_base, "PESABrain_ASLPerfusion_VascularAtlas_MeanCBF_20260216.xlsx", sheet="Sheet1", source_kind="image_wide")

In [4]:
# repo.get("source_tables").sort_values(["source_file", "source_sheet", "source_kind"])

In [5]:
repo.clinical(
    variables=["BPXSYM", "BMI", "tacsctot_group"],
    filters={
        # "subject_uid": ["PESA10407076", "PESA16016004"],
        # "bmi": {"$ge": 27, "$lt": 30}
    },
    wide=True,
)

       subject_uid visit_id        bmi bpxsym tacsctot_group
0     PESA10017225        4  30.119402  130.0             g1
1       PESA100489        4  22.662709  128.0             g0
2     PESA10048900        4        NaN  150.0             g1
3     PESA10055241        4  27.398176  117.0             g1
4      PESA1006009        4  27.968016  124.0             g0
...            ...      ...        ...    ...            ...
996    PESA9928801        4  27.041644  104.0             g0
997    PESA9935104        4  19.896194  122.0             g0
998    PESA9947716        4  29.757785  114.0             g1
999    PESA9954025        4  23.875659  126.0             g1
1000   PESA9972964        4  19.322185  109.0             g0

[1001 rows x 5 columns]

In [18]:
repo.image(
    modality="4dflow",
    data_version=1,
    # variables=["flow_mean"],
    regions=["right_ica"],
    wide=True,
)

      subject_uid  4dflow__right_ica__flow_mean  4dflow__right_ica__pi
0     PESA1006009                    281.351906               0.727263
1    PESA10061584                    207.560577               0.698219
2    PESA10067929                    355.117301               0.796976
3    PESA10086976                      0.814246               0.847596
4    PESA10112400                    330.478438               0.791426
..            ...                           ...                    ...
343   PESA9897316                    262.646432               0.782386
344   PESA9928801                    370.991649               0.870882
345   PESA9935104                    199.660541               0.735158
346   PESA9947716                    358.434131               0.811330
347   PESA9972964                    253.431541               0.742674

[348 rows x 3 columns]

In [12]:
repo.image(
    modality="asl",
    variables=['mean_cbf'],
    # regions=["right_ica"],
    atlas="vascular-8",
    wide=True,
)

,subject_uid,asl__left_aca_8__mean_cbf,asl__left_basilar_8__mean_cbf,asl__left_mca_8__mean_cbf,asl__left_pca_8__mean_cbf,asl__right_aca_8__mean_cbf,asl__right_basilar_8__mean_cbf,asl__right_mca_8__mean_cbf,asl__right_pca_8__mean_cbf,asl__watershed_8__mean_cbf
0,,45.831087,40.621590,47.245653,35.603938,47.587176,39.798200,48.180616,36.658410,41.674001
1,PESA10017225,54.748315,53.706869,55.329698,52.413142,55.075685,55.741001,55.305353,50.399999,45.768453
2,PESA1002001,45.890711,43.595341,50.949984,44.144234,46.676598,43.494788,50.105159,42.889667,40.066280
3,PESA100489,69.372262,73.106089,73.012827,66.389724,70.515337,70.898637,72.683254,66.693302,54.169724
4,PESA10055241,48.728630,51.617259,51.208784,43.545062,46.788938,48.530094,49.396042,42.430235,39.087144
...,...,...,...,...,...,...,...,...,...,...
1354,PESA9935104,52.431084,40.572026,54.236169,43.115527,50.796183,38.552160,54.130418,40.179098,46.629408
1355,PESA9947716,61.730753,49.490786,66.492889,50.254449,66.573847,50.701696,72.198803,49.731519,55.293241
1356,PESA9954025,50.173566,59.817856,53.479352,51.124338,51.770626,59.725848,50.970979,51.650691,43.565898
1357,PESA996004,35.530079,27.512319,36.425947,27.105437,32.436489,29.319548,31.538392,27.172000,26.031640
1358,PESA9972964,56.058626,45.547853,58.761334,48.897040,56.701499,46.652231,57.912745,47.255383,48.016116

In [19]:
clinical = repo.clinical(
    variables=["BPXSYM", "BMI", "tacsctot_group"],
    filters={"subject_uid": ["PESA10407076", "PESA16016004"]},
    wide=True,
)

hemo = repo.image(
    modality="4dflow",
    variables=["flow_mean", 'pi'],
    regions=["right_ica", "left_ica"],
    data_version=1,
    wide=True,
)

report_df = repo.join([clinical, hemo])
report_df.head()

,subject_uid,visit_id,bmi,bpxsym,tacsctot_group,4dflow__left_ica__flow_mean,4dflow__left_ica__pi,4dflow__right_ica__flow_mean,4dflow__right_ica__pi
0,PESA10407076,4,29.011226,137.0,g1,336.984932,0.698981,346.493410,0.719224
1,PESA16016004,4,25.099502,121.0,g1,438.522579,0.929726,397.337101,0.939473

In [ ]:
# import_pesabrain_source(
#     repo,
#     db_base,
#     "PESABrain_ASLPerfusion_CovCBF_20260216.xlsx",
#     sheet="Sheet1",
#     source_kind="image_wide",
# )

# repo.image(
#     modality="asl",
#     variables=["cov_cbf"],
#     atlas="desikan",
#     wide=True,
# )

,subject_uid,session_id,asl__ctx_left_anterior_cingulate__cov_cbf,asl__ctx_left_frontal_lobe__cov_cbf,asl__ctx_left_hemisphere__cov_cbf,asl__ctx_left_occipital_lobe__cov_cbf,asl__ctx_left_parietal_lobe__cov_cbf,asl__ctx_left_temporal_lobe__cov_cbf,asl__ctx_lh_bankssts__cov_cbf,asl__ctx_lh_caudalanteriorcingulate__cov_cbf,...,asl__ctx_rh_supramarginal__cov_cbf,asl__ctx_rh_temporalpole__cov_cbf,asl__ctx_rh_transversetemporal__cov_cbf,asl__ctx_right_anterior_cingulate__cov_cbf,asl__ctx_right_frontal_lobe__cov_cbf,asl__ctx_right_hemisphere__cov_cbf,asl__ctx_right_occipital_lobe__cov_cbf,asl__ctx_right_parietal_lobe__cov_cbf,asl__ctx_right_temporal_lobe__cov_cbf,asl__ctx_whole_brain__cov_cbf
0,PESA10017225,BMRI613225,0.452060,0.472829,0.560015,0.620081,0.590010,0.651455,0.542885,0.287351,...,0.501129,0.579615,0.374256,0.390560,0.464650,0.557169,0.600517,0.584465,0.681216,0.558625
1,PESA1002001,IA706156,0.395617,0.544135,0.611366,0.576589,0.639490,0.700544,0.587060,0.353848,...,0.552336,0.528527,0.370642,0.406422,0.525181,0.583345,0.574381,0.639043,0.626311,0.597330
2,PESA100489,BMRI649274,0.527712,0.543879,0.643825,0.682902,0.716763,0.722049,0.778027,0.402595,...,0.504942,0.607363,0.392171,0.490312,0.534953,0.636887,0.726292,0.683077,0.726770,0.640423
3,PESA10055241,BMRI872431,0.426895,0.448705,0.553270,0.661140,0.557523,0.694156,0.601335,0.287250,...,0.424982,0.799478,0.355929,0.388077,0.439817,0.533953,0.620370,0.546580,0.650340,0.543731
4,PESA1006009,BMRI923674,0.518955,0.533282,0.563952,0.551462,0.546076,0.660492,0.500050,0.318890,...,0.492034,0.734295,0.321753,0.464139,0.502499,0.548704,0.561752,0.525568,0.662551,0.556577
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1378,PESA9935104,BMRI881199,0.405067,0.473152,0.518197,0.564974,0.534482,0.557154,0.507536,0.371898,...,0.460791,0.549321,0.170726,0.396846,0.494713,0.556186,0.591173,0.569271,0.638182,0.537029
1379,PESA9947716,BMRI447102,0.381084,0.456018,0.570185,0.597395,0.618159,0.685539,0.589018,0.299786,...,0.457169,0.472424,0.316467,0.300117,0.456946,0.560157,0.573520,0.601857,0.688001,0.566396
1380,PESA9954025,BMRI971103,0.472588,0.493494,0.565424,0.604163,0.582947,0.666161,0.568104,0.302939,...,0.495543,0.600872,0.289030,0.422153,0.484560,0.545574,0.553304,0.561335,0.636993,0.555460
1381,PESA996004,IA192427,0.827544,0.663378,0.722074,0.682393,0.694752,0.808883,0.643079,0.571278,...,0.585958,0.580459,0.434666,0.588588,0.636693,0.722169,0.655451,0.723059,0.810111,0.724639
1382,PESA9972964,BMRI105334,0.408378,0.504800,0.579825,0.648434,0.597248,0.674092,0.600755,0.306917,...,0.555574,0.599855,0.337562,0.384505,0.499499,0.566991,0.593799,0.574100,0.671367,0.573412

In [ ]:
# Remove

# empty = repo.get("subject_ids").iloc[0:0]
# repo.write_table("subject_ids", empty, provenance={"importer": "undo batch {trial_id}"})

# empty = repo.get("clinical_measurements").iloc[0:0]
# repo.write_table("clinical_measurements", empty, provenance={"importer": "undo batch {trial_id}"})

# empty = repo.get("image_measurements").iloc[0:0]
# repo.write_table("image_measurements", empty, provenance={"importer": "undo batch {trial_id}"})

# src = repo.get("source_tables")
# src = src[src["source_batch_id"] != trial_id]
# repo.write_table(
#   "source_tables",
#   src,
#   provenance={"reason": f"undo batch {trial_id}"},
# )

PosixPath('/home/imarcoss/nvitk/notebooks/prototypes/dataset/tables/image_measurements.parquet')