In [1]:
import os
import sys
from pathlib import Path

ROOT = Path(os.path.abspath('')).resolve().parents[2]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))


import nvitk as nv
from nvitk import db
import pandas as pd

Build DB

In [2]:
from nvitk.db import DataRepo, import_pesabrain_source, list_pesabrain_sources

db_base = Path("/data_local/LabVF/PESA-Brain/DB/DB")
repo = DataRepo("~/nvitk/dataset", use_sqlite=True) # , auto_scaffold=True

In [ ]:
# res = import_pesabrain_source(
#     repo,
#     db_base,
#     "PESABrain_All_IDs.xlsx",
#     sheet="Sheet1",
#     source_kind="subject_ids",
#     build_sqlite_index=True,
# )

# res = import_pesabrain_source(
#     repo,
#     db_base,
#     "PESABrain_All_4DFlow_IDs.xlsx",
#     sheet="Sheet1",
#     source_kind="subject_ids",
#     build_sqlite_index=True,
# )

# import_pesabrain_source(
#     repo,
#     db_base,
#     "PESABrain_SubjectCatalog_AllXNAT_20260216.xlsx",
#     sheet="Datos",
#     source_kind="subject_catalog",
#     build_sqlite_index=True,
# )

# import_pesabrain_source(
#     repo,
#     db_base,
#     "PESABrain_Clinical_20260216.xlsx",
#     sheet="Sheet1",
#     source_kind="clinical_wide",
#     build_sqlite_index=True,
# )

# import_pesabrain_source(repo, db_base, "PESABrain_APOE_20260318.xlsx", sheet="Sheet1", source_kind="clinical_wide", build_sqlite_index=True)
# import_pesabrain_source(repo, db_base, "PESABrain_TAC_20260318.xlsx", sheet="Sheet1", source_kind="clinical_wide", build_sqlite_index=True)
# import_pesabrain_source(repo, db_base, "PESABrain_Echography_CarotidePlaque_20260216.xlsx", sheet="Sheet1", source_kind="clinical_wide", build_sqlite_index=True)

# import_pesabrain_source(repo, db_base, "PESABrain_4DFlow_LocalizedPI_20260216.xlsx", sheet="PESABrain_AnalysisDB_Batch1", source_kind="image_wide", build_sqlite_index=True)
# import_pesabrain_source(repo, db_base, "PESABrain_4DFlow_LocalizedTimeAvgFlow_20260216.xlsx", sheet="PESABrain_AnalysisDB_Batch1", source_kind="image_wide", build_sqlite_index=True)

# import_pesabrain_source(repo, db_base, "PESABrain_4DFlow_LocalizedTimeseriesFlow_Wide_20260216.xlsx", sheet="Datos", source_kind="image_timeseries_wide", build_sqlite_index=True)

# import_pesabrain_source(repo, db_base, "PESABrain_ASLPerfusion_ThrMeanCBF_20260216.xlsx", sheet="Sheet1", source_kind="image_wide", build_sqlite_index=True)
# import_pesabrain_source(repo, db_base, "PESABrain_ASLPerfusion_VascularAtlas_MeanCBF_20260216.xlsx", sheet="Sheet1", source_kind="image_wide", build_sqlite_index=True)
# import_pesabrain_source(
#     repo,
#     db_base,
#     "PESABrain_ASLPerfusion_CovCBF_20260216.xlsx",
#     sheet="Sheet1",
#     source_kind="image_wide",
#     build_sqlite_index=True,
# )

{'filename': 'PESABrain_ASLPerfusion_CovCBF_20260216.xlsx',
 'sheet': 'Sheet1',
 'source_kind': 'image_wide',
 'result':          subject_uid  session_id modality      region_id   region_label  \
 0       PESA10017225  BMRI613225      asl     patient_id     patient_id
 1        PESA1002001    IA706156      asl     patient_id     patient_id
 2         PESA100489  BMRI649274      asl     patient_id     patient_id
 3       PESA10055241  BMRI872431      asl     patient_id     patient_id
 4        PESA1006009  BMRI923674      asl     patient_id     patient_id
 ...              ...         ...      ...            ...            ...
 113401   PESA9935104  BMRI881199      asl  ctx_rh_insula  ctx-rh-insula
 113402   PESA9947716  BMRI447102      asl  ctx_rh_insula  ctx-rh-insula
 113403   PESA9954025  BMRI971103      asl  ctx_rh_insula  ctx-rh-insula
 113404    PESA996004    IA192427      asl  ctx_rh_insula  ctx-rh-insula
 113405   PESA9972964  BMRI105334      asl  ctx_rh_insula  ctx-rh-insula

         frame_index variable_id  value_num    value_text  unit  ...  \
 0              <NA>     cov_cbf        NaN  PESA10017225  <NA>  ...
 1              <NA>     cov_cbf        NaN   PESA1002001  <NA>  ...
 2              <NA>     cov_cbf        NaN    PESA100489  <NA>  ...
 3              <NA>     cov_cbf        NaN  PESA10055241  <NA>  ...
 4              <NA>     cov_cbf        NaN   PESA1006009  <NA>  ...
 ...             ...         ...        ...           ...   ...  ...
 113401         <NA>     cov_cbf   0.484859          <NA>  <NA>  ...
 113402         <NA>     cov_cbf   0.415895          <NA>  <NA>  ...
 113403         <NA>     cov_cbf   0.515698          <NA>  <NA>  ...
 113404         <NA>     cov_cbf   0.694183          <NA>  <NA>  ...
 113405         <NA>     cov_cbf   0.427383          <NA>  <NA>  ...

                                  pipeline_name pipeline_id qc_status  \
 0       PESABrain_ASLPerfusion_CovCBF_20260216      asl_v1      <NA>
 1       PESABrain_ASLPerfusion_CovCBF_20260216      asl_v1      <NA>
 2       PESABrain_ASLPerfusion_CovCBF_20260216      asl_v1      <NA>
 3       PESABrain_ASLPerfusion_CovCBF_20260216      asl_v1      <NA>
 4       PESABrain_ASLPerfusion_CovCBF_20260216      asl_v1      <NA>
 ...                                        ...         ...       ...
 113401  PESABrain_ASLPerfusion_CovCBF_20260216      asl_v1      <NA>
 113402  PESABrain_ASLPerfusion_CovCBF_20260216      asl_v1      <NA>
 113403  PESABrain_ASLPerfusion_CovCBF_20260216      asl_v1      <NA>
 113404  PESABrain_ASLPerfusion_CovCBF_20260216      asl_v1      <NA>
 113405  PESABrain_ASLPerfusion_CovCBF_20260216      asl_v1      <NA>

        source_asset                                    source_table  \
 0              <NA>  PESABrain_ASLPerfusion_CovCBF_20260216::Sheet1
 1              <NA>  PESABrain_ASLPerfusion_CovCBF_20260216::Sheet1
 2              <NA>  PESABrain_ASLPerfusion_CovCBF_20260216::Sheet1
 3              <NA>  PESABrain_ASLPerfusion_CovCBF_20260216::Sheet1
 4              <NA>  PESABrain_ASLPerfusion_CovCBF_20260216::Sheet1
 ...             ...                                             ...
 113401         <NA>  PESABrain_ASLPerfusion_CovCBF_20260216::Sheet1
 113402         <NA>  PESABrain_ASLPerfusion_CovCBF_20260216::Sheet1
 113403         <NA>  PESABrain_ASLPerfusion_CovCBF_20260216::Sheet1
 113404         <NA>  PESABrain_ASLPerfusion_CovCBF_20260216::Sheet1
 113405         <NA>  PESABrain_ASLPerfusion_CovCBF_20260216::Sheet1

                                         source_file source_sheet  \
 0       PESABrain_ASLPerfusion_CovCBF_20260216.xlsx       Sheet1
 1       PESABrain_ASLPerfusion_CovCBF_20260216.xlsx       Sheet1
 2       PESABrain_ASLPerfusion_CovCBF_20260216.xlsx       Sheet1
 3       PESABrain_ASLPerfusion_CovCBF_20260216.xlsx       Sheet1
 4       PESABrain_ASLPerfusion_CovCBF_20260216.xlsx       Sheet1
 ...                                             ...          ...
 113401  PESABrain_ASLPerfusion_CovCBF_20260216.xlsx       Sheet1
 113402  PESABrain_ASLPerfusion_CovCBF_20260216.xlsx       Sheet1
 113403  PESABrain_ASLPerfusion_CovCBF_20260216.xlsx       Sheet1
 113404  PESABrain_ASLPerfusion_CovCBF_20260216.xlsx       Sheet1
 113405  PESABrain_ASLPerfusion_CovCBF_20260216.xlsx       Sheet1

         source_column                 source_batch_id measured_at
 0          patient_id  pesabrain_20260411T113803+0000         NaT
 1          patient_id  pesabrain_20260411T113803+0000         NaT
 2          patient_id  pesabrain_20260411T113803+0000         NaT
 3          patient_id  pesabrain_20260411T113803+0000         NaT
 4          patient_id  pesabrain_20260411T113803+0000         NaT
 ...               ...                             ...         ...
 113401  ctx-rh-insula  pesabrain_20260411T113803+0000         NaT
 113402  ctx-rh-insula  pesabrain_20260411T113803+0000         NaT
 113403  ctx-rh-insula  pesabrain_20260411T113803+0000         NaT
 113404  ctx-rh-insula  pesabrain_20260411T113803+0000         NaT
 113405  ctx-rh-insula  pesabrain_20260411T113803+0000         NaT

 [113406 rows x 21 columns],
 'subjects':        subject_uid primary_patient_id primary_seqn     sex birth_date notes  \
 0          PESA841            PESA841           28    Male        NaT  <NA>
 1          PESA900            PESA900           29  Female        NaT  <NA>
 2         PESA3481           PESA3481           58    Male        NaT  <NA>
 3         PESA3600           PESA3600           59    Male        NaT  <NA>
 4         PESA4225           PESA4225           64  Female        NaT  <NA>
 ...            ...                ...          ...     ...        ...   ...
 1419    PESA894916         PESA894916          NaN     NaN        NaT  <NA>
 1420  PESA17089956       PESA17089956          NaN     NaN        NaT  <NA>
 1421     PESA31329          PESA31329          NaN     NaN        NaT  <NA>
 1422      PESA5476           PESA5476          NaN     NaN        NaT  <NA>
 1423  PESA13461561       PESA13461561          NaN     NaN        NaT  <NA>

        source_batch_id                 updated_at
 0     derived_subjects  2026-04-11T11:38:17+00:00
 1     derived_subjects  2026-04-11T11:38:17+00:00
 2     derived_subjects  2026-04-11T11:38:17+00:00
 3     derived_subjects  2026-04-11T11:38:17+00:00
 4     derived_subjects  2026-04-11T11:38:17+00:00
 ...                ...                        ...
 1419  derived_subjects  2026-04-11T11:38:33+00:00
 1420  derived_subjects  2026-04-11T11:38:33+00:00
 1421  derived_subjects  2026-04-11T11:38:33+00:00
 1422  derived_subjects  2026-04-11T11:38:33+00:00
 1423  derived_subjects  2026-04-11T11:38:33+00:00

 [1424 rows x 8 columns]}

In [ ]:
# repo.drop_all_tables()

In [4]:
# repo.get("source_tables").sort_values(["source_file", "source_sheet", "source_kind"])

In [3]:
repo.clinical(
    variables=["BPXSYM", "BMI", "tacsctot_group"],
    filters={
        # "subject_uid": ["PESA10407076", "PESA16016004"],
        # "bmi": {"$ge": 27, "$lt": 30}
    },
    # wide=True,
)

       subject_uid visit_id        bmi bpxsym tacsctot_group
0     PESA10017225        4  30.119402  130.0             g1
1       PESA100489        4  22.662709  128.0             g0
2     PESA10048900        4        NaN  150.0             g1
3     PESA10055241        4  27.398176  117.0             g1
4      PESA1006009        4  27.968016  124.0             g0
...            ...      ...        ...    ...            ...
996    PESA9928801        4  27.041644  104.0             g0
997    PESA9935104        4  19.896194  122.0             g0
998    PESA9947716        4  29.757785  114.0             g1
999    PESA9954025        4  23.875659  126.0             g1
1000   PESA9972964        4  19.322185  109.0             g0

[1001 rows x 5 columns]

In [4]:
repo.image(
    modality="4dflow",
    variables=["flow_mean", 'pi'],
    regions=["right_ica", "left_ica", 'basilar'],
    # wide=True,
)

,subject_uid,session_id,basilar_flow_mean,basilar_pi,left_ica_flow_mean,left_ica_pi,right_ica_flow_mean,right_ica_pi
0,PESA1006009,BMRI923674,184.510389,0.791092,267.035802,0.701133,281.351906,0.727263
1,PESA10061584,BMRI287356,182.850943,0.819871,94.844843,0.639911,207.560577,0.698219
2,PESA10067929,BMRI965424,228.640571,0.810012,323.586469,0.773645,355.117301,0.796976
3,PESA10086976,BMRI859483,251.966084,0.657827,303.364359,0.540127,0.814246,0.847596
4,PESA10112400,BMRI465140,151.450536,0.657464,325.856177,0.707761,330.478438,0.791426
...,...,...,...,...,...,...,...,...
343,PESA9897316,BMRI994162,178.221377,0.674136,283.497145,0.709040,262.646432,0.782386
344,PESA9928801,BMRI487416,87.832792,0.567656,314.992869,0.850857,370.991649,0.870882
345,PESA9935104,BMRI881199,245.827435,0.719752,352.592480,0.753206,199.660541,0.735158
346,PESA9947716,BMRI447102,309.712580,0.857074,350.185589,0.807655,358.434131,0.811330
347,PESA9972964,BMRI105334,183.211070,0.688649,301.500929,0.668324,253.431541,0.742674

In [5]:
repo.image(
    modality="4dflow",
    # pipeline="pesabrain_4dflow_current",
    variables=["flow_tseries"],
    regions=["right_ica", "left_ica", 'basi'],
    wide=True,
    use_sqlite=True,
)

,subject_uid,session_id,basi,basi_f1,basi_f10,basi_f11,basi_f12,basi_f13,basi_f14,basi_f2,basi_f3,basi_f4,basi_f5,basi_f6,basi_f7,basi_f8,basi_f9
0,PESA1006009,,171.740742,168.193645,262.681961,237.725158,188.848443,191.011362,189.220390,152.294641,138.217177,136.751847,130.361080,120.433002,160.840273,252.938347,266.397772
1,PESA10061584,,167.251668,155.436301,251.961823,186.144733,178.125043,174.001665,166.416178,151.897402,130.579791,123.068390,117.425623,159.254665,256.388626,267.339821,257.472410
2,PESA10067929,,234.015326,209.301810,331.168985,309.251060,264.493818,242.809982,229.040794,190.483975,179.451871,173.877940,162.381248,145.967445,177.177801,264.656296,315.530205
3,PESA10086976,,200.100117,181.868849,237.502127,246.950941,232.032981,216.727839,218.705420,175.903559,195.263457,289.014559,323.399076,341.653547,332.864256,311.874561,275.629978
4,PESA10112400,,139.311733,126.335349,205.431976,183.801470,159.936533,156.501975,155.314536,122.262626,115.729229,114.442914,112.360876,114.743800,146.442618,207.208228,211.934180
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
337,PESA9897316,,146.445465,146.135516,189.702344,170.771270,172.337880,168.572130,159.571881,138.917656,132.200232,127.832479,170.140100,240.659351,236.923871,247.977991,225.132494
338,PESA9928801,,78.387072,73.397763,118.553166,109.357817,90.608840,91.994212,86.635509,71.107993,69.733021,69.948456,68.694377,70.771401,97.363837,114.649208,114.833064
339,PESA9935104,,229.139428,203.757019,351.813755,317.140303,256.308432,260.468359,243.036089,207.432761,199.516983,187.837157,174.878869,180.644660,228.866200,321.558523,325.012980
340,PESA9947716,,253.525257,221.942196,273.990383,287.376165,289.021425,284.843245,276.262808,203.814025,199.518857,273.705168,464.965525,454.760971,426.791239,386.633577,348.537855
341,PESA9972964,,197.611041,180.883598,245.183058,252.565899,241.381731,212.511535,210.013647,169.744234,160.409818,147.973294,139.340687,129.881787,132.475276,126.397777,201.792669

In [12]:
repo.image(
    modality="asl",
    variables=['mean_cbf'],
    # regions=["right_ica"],
    atlas="desikan",
    wide=True,
    use_sqlite=True,
)

,subject_uid,session_id,ctx_left_anterior_cingulate,ctx_left_frontal_lobe,ctx_left_hemisphere,ctx_left_occipital_lobe,ctx_left_parietal_lobe,ctx_left_temporal_lobe,ctx_lh_bankssts,ctx_lh_caudalanteriorcingulate,...,ctx_rh_supramarginal,ctx_rh_temporalpole,ctx_rh_transversetemporal,ctx_right_anterior_cingulate,ctx_right_frontal_lobe,ctx_right_hemisphere,ctx_right_occipital_lobe,ctx_right_parietal_lobe,ctx_right_temporal_lobe,ctx_whole_brain
0,PESA10017225,BMRI613225,64.108216,65.458659,61.897253,56.170527,62.396216,56.541516,64.038344,67.557323,...,65.805750,52.896903,94.734164,70.327429,66.677251,62.871607,57.386706,62.975389,57.127302,62.389454
1,PESA1002001,IA706156,58.723609,52.989686,55.773419,60.135660,56.405732,54.849913,87.514262,67.551766,...,58.937474,55.399962,86.935706,58.474634,54.133276,55.731381,57.767403,56.196220,54.906978,55.751993
2,PESA100489,BMRI649274,87.214877,76.428488,73.555987,68.583159,68.530902,71.110262,72.251565,102.378239,...,85.157223,53.573930,123.434005,89.153019,78.027298,73.559161,65.177234,70.570929,69.668548,73.557550
3,PESA10055241,BMRI872431,57.442981,58.200862,55.306647,48.994470,55.218977,50.945834,64.805005,65.584888,...,59.737115,39.929875,85.994163,54.434933,57.211294,54.878386,48.371067,55.735338,51.788467,55.091414
4,PESA1006009,BMRI923674,68.255060,61.740562,63.393821,68.494657,65.866269,55.974345,65.231328,87.196869,...,66.337672,63.197503,101.617334,71.187907,67.408806,66.288385,69.423112,66.219254,59.196456,64.850706
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1378,PESA9935104,BMRI881199,55.811071,61.096123,57.807313,49.279588,60.576383,52.312585,62.371022,57.817307,...,60.765123,42.351298,94.461272,59.523966,59.512227,55.979328,49.214372,57.947922,50.774988,56.903359
1379,PESA9947716,BMRI447102,71.170601,74.731206,69.965742,60.644756,70.948384,62.829321,88.761006,83.577222,...,81.980738,54.961856,121.530419,82.271338,81.009304,74.834474,64.227081,74.830753,66.725016,72.428656
1380,PESA9954025,BMRI971103,65.226978,60.358033,59.377463,60.964903,58.965748,55.114155,62.779410,75.575217,...,65.520952,44.724364,112.838517,69.849831,61.292834,59.850783,58.694509,58.779466,55.479826,59.616568
1381,PESA996004,IA192427,45.505831,39.947504,41.080146,38.991172,40.303477,42.355687,44.566342,48.221394,...,39.586373,48.949522,83.811986,40.148030,34.785846,37.419248,33.302293,37.361973,40.334107,39.217882
1382,PESA9972964,BMRI105334,60.014801,64.614286,61.776127,53.121316,65.587765,56.777678,56.897966,70.174414,...,67.255690,46.138130,103.784023,59.201978,65.579722,62.464305,53.374576,65.579486,57.195454,62.120475

In [8]:
clinical = repo.clinical(
    variables=["BPXSYM", "BMI", "tacsctot_group"],
    filters={"subject_uid": ["PESA10407076", "PESA16016004"]},
    wide=True,
)

hemo = repo.image(
    modality="4dflow",
    variables=["flow_mean", 'pi'],
    regions=["right_ica", "left_ica"],
    pipeline="legacy",
    wide=True,
)

report_df = repo.join([clinical, hemo])
report_df.head()

,subject_uid,visit_id,bmi,bpxsym,tacsctot_group,session_id,left_ica_flow_mean,left_ica_pi,right_ica_flow_mean,right_ica_pi
0,PESA10407076,4,29.011226,137.0,g1,BMRI395267,336.984932,0.698981,346.493410,0.719224
1,PESA16016004,4,25.099502,121.0,g1,BMRI611724,438.522579,0.929726,397.337101,0.939473

In [27]:
# repo.build_sqlite_index()

PosixPath('/home/imarcoss/nvitk/dataset/cache/index.sqlite')

In [ ]:
# import_pesabrain_source(
#     repo,
#     db_base,
#     "PESABrain_ASLPerfusion_CovCBF_20260216.xlsx",
#     sheet="Sheet1",
#     source_kind="image_wide",
# )

repo.image(
    modality="asl",
    variables=["cov_cbf"],
    atlas="desikan",
    wide=True,
)

,subject_uid,session_id,asl__ctx_left_anterior_cingulate__cov_cbf,asl__ctx_left_frontal_lobe__cov_cbf,asl__ctx_left_hemisphere__cov_cbf,asl__ctx_left_occipital_lobe__cov_cbf,asl__ctx_left_parietal_lobe__cov_cbf,asl__ctx_left_temporal_lobe__cov_cbf,asl__ctx_lh_bankssts__cov_cbf,asl__ctx_lh_caudalanteriorcingulate__cov_cbf,...,asl__ctx_rh_supramarginal__cov_cbf,asl__ctx_rh_temporalpole__cov_cbf,asl__ctx_rh_transversetemporal__cov_cbf,asl__ctx_right_anterior_cingulate__cov_cbf,asl__ctx_right_frontal_lobe__cov_cbf,asl__ctx_right_hemisphere__cov_cbf,asl__ctx_right_occipital_lobe__cov_cbf,asl__ctx_right_parietal_lobe__cov_cbf,asl__ctx_right_temporal_lobe__cov_cbf,asl__ctx_whole_brain__cov_cbf
0,PESA10017225,BMRI613225,0.452060,0.472829,0.560015,0.620081,0.590010,0.651455,0.542885,0.287351,...,0.501129,0.579615,0.374256,0.390560,0.464650,0.557169,0.600517,0.584465,0.681216,0.558625
1,PESA1002001,IA706156,0.395617,0.544135,0.611366,0.576589,0.639490,0.700544,0.587060,0.353848,...,0.552336,0.528527,0.370642,0.406422,0.525181,0.583345,0.574381,0.639043,0.626311,0.597330
2,PESA100489,BMRI649274,0.527712,0.543879,0.643825,0.682902,0.716763,0.722049,0.778027,0.402595,...,0.504942,0.607363,0.392171,0.490312,0.534953,0.636887,0.726292,0.683077,0.726770,0.640423
3,PESA10055241,BMRI872431,0.426895,0.448705,0.553270,0.661140,0.557523,0.694156,0.601335,0.287250,...,0.424982,0.799478,0.355929,0.388077,0.439817,0.533953,0.620370,0.546580,0.650340,0.543731
4,PESA1006009,BMRI923674,0.518955,0.533282,0.563952,0.551462,0.546076,0.660492,0.500050,0.318890,...,0.492034,0.734295,0.321753,0.464139,0.502499,0.548704,0.561752,0.525568,0.662551,0.556577
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1378,PESA9935104,BMRI881199,0.405067,0.473152,0.518197,0.564974,0.534482,0.557154,0.507536,0.371898,...,0.460791,0.549321,0.170726,0.396846,0.494713,0.556186,0.591173,0.569271,0.638182,0.537029
1379,PESA9947716,BMRI447102,0.381084,0.456018,0.570185,0.597395,0.618159,0.685539,0.589018,0.299786,...,0.457169,0.472424,0.316467,0.300117,0.456946,0.560157,0.573520,0.601857,0.688001,0.566396
1380,PESA9954025,BMRI971103,0.472588,0.493494,0.565424,0.604163,0.582947,0.666161,0.568104,0.302939,...,0.495543,0.600872,0.289030,0.422153,0.484560,0.545574,0.553304,0.561335,0.636993,0.555460
1381,PESA996004,IA192427,0.827544,0.663378,0.722074,0.682393,0.694752,0.808883,0.643079,0.571278,...,0.585958,0.580459,0.434666,0.588588,0.636693,0.722169,0.655451,0.723059,0.810111,0.724639
1382,PESA9972964,BMRI105334,0.408378,0.504800,0.579825,0.648434,0.597248,0.674092,0.600755,0.306917,...,0.555574,0.599855,0.337562,0.384505,0.499499,0.566991,0.593799,0.574100,0.671367,0.573412

In [ ]:
# Remove

# empty = repo.get("subject_ids").iloc[0:0]
# repo.write_table("subject_ids", empty, provenance={"importer": "undo batch {trial_id}"})

# empty = repo.get("clinical_measurements").iloc[0:0]
# repo.write_table("clinical_measurements", empty, provenance={"importer": "undo batch {trial_id}"})

# empty = repo.get("image_measurements").iloc[0:0]
# repo.write_table("image_measurements", empty, provenance={"importer": "undo batch {trial_id}"})

# src = repo.get("source_tables")
# src = src[src["source_batch_id"] != trial_id]
# repo.write_table(
#   "source_tables",
#   src,
#   provenance={"reason": f"undo batch {trial_id}"},
# )

PosixPath('/home/imarcoss/nvitk/notebooks/prototypes/dataset/tables/image_measurements.parquet')