In [1]:
import os
import sys
from pathlib import Path

ROOT = Path(os.path.abspath('')).resolve().parents[2]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))


import nvitk as nv
from nvitk import db
import pandas as pd

Build DB

In [2]:
from nvitk.db import DataRepo, import_pesabrain_source, list_pesabrain_sources

db_base = Path("/data_local/LabVF/PESA-Brain/DB/DB")
repo = DataRepo("~/nvitk/dataset", auto_scaffold=True, use_sqlite=True) # , auto_scaffold=True

In [ ]:
# res = import_pesabrain_source(
#     repo,
#     db_base,
#     "PESABrain_All_IDs.xlsx",
#     sheet="Sheet1",
#     source_kind="subject_ids",
#     build_sqlite_index=True,
# )

# res = import_pesabrain_source(
#     repo,
#     db_base,
#     "PESABrain_All_4DFlow_IDs.xlsx",
#     sheet="Sheet1",
#     source_kind="subject_ids",
#     build_sqlite_index=True,
# )

# import_pesabrain_source(
#     repo,
#     db_base,
#     "PESABrain_SubjectCatalog_AllXNAT_20260216.xlsx",
#     sheet="Datos",
#     source_kind="subject_catalog",
#     build_sqlite_index=True,
# )

# import_pesabrain_source(
#     repo,
#     db_base,
#     "PESABrain_Clinical_20260216.xlsx",
#     sheet="Sheet1",
#     source_kind="clinical_wide",
#     build_sqlite_index=True,
# )

# import_pesabrain_source(repo, db_base, "PESABrain_APOE_20260318.xlsx", sheet="Sheet1", source_kind="clinical_wide", build_sqlite_index=True)
# import_pesabrain_source(repo, db_base, "PESABrain_TAC_20260318.xlsx", sheet="Sheet1", source_kind="clinical_wide", build_sqlite_index=True)
# import_pesabrain_source(repo, db_base, "PESABrain_Echography_CarotidePlaque_20260216.xlsx", sheet="Sheet1", source_kind="clinical_wide", build_sqlite_index=True)

# import_pesabrain_source(repo, db_base, "PESABrain_4DFlow_LocalizedPI_20260216.xlsx", sheet="PESABrain_AnalysisDB_Batch1", source_kind="image_wide", build_sqlite_index=True)
# import_pesabrain_source(repo, db_base, "PESABrain_4DFlow_LocalizedTimeAvgFlow_20260216.xlsx", sheet="PESABrain_AnalysisDB_Batch1", source_kind="image_wide", build_sqlite_index=True)
# import_pesabrain_source(repo, db_base, "PESABrain_4DFlow_LocalizedTimeseriesFlow_Wide_20260216.xlsx", sheet="Datos", source_kind="image_timeseries_wide", build_sqlite_index=True)

# import_pesabrain_source(repo, db_base, "PESABrain_4DFlowv2_LocalizedPI_202602410.xlsx", pipeline_id='4dflow_v2', sheet="Sheet1", source_kind="image_wide", build_sqlite_index=True)
# import_pesabrain_source(repo, db_base, "PESABrain_4DFlowv2_LocalizedTimeAvgFlow_202602410.xlsx", pipeline_id='4dflow_v2', sheet="Sheet1", source_kind="image_wide", build_sqlite_index=True)
# import_pesabrain_source(repo, db_base, "PESABrain_4DFlowv2_LocalizedTimeseriesFlow_Wide_202602410.xlsx", pipeline_id='4dflow_v2', sheet="Sheet1", source_kind="image_timeseries_wide", build_sqlite_index=True)

# import_pesabrain_source(repo, db_base, "PESABrain_ASLPerfusion_ThrMeanCBF_20260216.xlsx", sheet="Sheet1", source_kind="image_wide", build_sqlite_index=True)
# import_pesabrain_source(repo, db_base, "PESABrain_ASLPerfusion_VascularAtlas_MeanCBF_20260216.xlsx", sheet="Sheet1", source_kind="image_wide", build_sqlite_index=True)
# import_pesabrain_source(
#     repo,
#     db_base,
#     "PESABrain_ASLPerfusion_CovCBF_20260216.xlsx",
#     sheet="Sheet1",
#     source_kind="image_wide",
#     build_sqlite_index=True,
# )

{'filename': 'PESABrain_4DFlowv2_LocalizedTimeAvgFlow_202602410.xlsx',
 'sheet': 'Sheet1',
 'source_kind': 'image_wide',
 'result':        subject_uid  session_id modality            region_id  \
 0      PESA1006009  BMRI923674   4dflow           patient_id
 1     PESA10061584  BMRI287356   4dflow           patient_id
 2     PESA10067929  BMRI965424   4dflow           patient_id
 3     PESA10086976  BMRI859483   4dflow           patient_id
 4     PESA10112400  BMRI465140   4dflow           patient_id
 ...            ...         ...      ...                  ...
 4993   PESA8737936  BMRI484487   4dflow  right_communicating
 4994   PESA8856576  BMRI223186   4dflow  right_communicating
 4995   PESA8910225  BMRI657181   4dflow  right_communicating
 4996   PESA9120400  BMRI535084   4dflow  right_communicating
 4997   PESA9928801  BMRI487416   4dflow  right_communicating

              region_label  frame_index variable_id   value_num    value_text  \
 0              patient_id         <NA>   flow_mean         NaN   PESA1006009
 1              patient_id         <NA>   flow_mean         NaN  PESA10061584
 2              patient_id         <NA>   flow_mean         NaN  PESA10067929
 3              patient_id         <NA>   flow_mean         NaN  PESA10086976
 4              patient_id         <NA>   flow_mean         NaN  PESA10112400
 ...                   ...          ...         ...         ...           ...
 4993  Right Communicating         <NA>   flow_mean   51.353716          <NA>
 4994  Right Communicating         <NA>   flow_mean  101.228214          <NA>
 4995  Right Communicating         <NA>   flow_mean   28.494200          <NA>
 4996  Right Communicating         <NA>   flow_mean   55.995817          <NA>
 4997  Right Communicating         <NA>   flow_mean   67.620200          <NA>

       unit  ...                                      pipeline_name  \
 0     <NA>  ...  PESABrain_4DFlowv2_LocalizedTimeAvgFlow_202602410
 1     <NA>  ...  PESABrain_4DFlowv2_LocalizedTimeAvgFlow_202602410
 2     <NA>  ...  PESABrain_4DFlowv2_LocalizedTimeAvgFlow_202602410
 3     <NA>  ...  PESABrain_4DFlowv2_LocalizedTimeAvgFlow_202602410
 4     <NA>  ...  PESABrain_4DFlowv2_LocalizedTimeAvgFlow_202602410
 ...    ...  ...                                                ...
 4993  <NA>  ...  PESABrain_4DFlowv2_LocalizedTimeAvgFlow_202602410
 4994  <NA>  ...  PESABrain_4DFlowv2_LocalizedTimeAvgFlow_202602410
 4995  <NA>  ...  PESABrain_4DFlowv2_LocalizedTimeAvgFlow_202602410
 4996  <NA>  ...  PESABrain_4DFlowv2_LocalizedTimeAvgFlow_202602410
 4997  <NA>  ...  PESABrain_4DFlowv2_LocalizedTimeAvgFlow_202602410

      pipeline_id qc_status source_asset  \
 0      4dflow_v2      <NA>         <NA>
 1      4dflow_v2      <NA>         <NA>
 2      4dflow_v2      <NA>         <NA>
 3      4dflow_v2      <NA>         <NA>
 4      4dflow_v2      <NA>         <NA>
 ...          ...       ...          ...
 4993   4dflow_v2      <NA>         <NA>
 4994   4dflow_v2      <NA>         <NA>
 4995   4dflow_v2      <NA>         <NA>
 4996   4dflow_v2      <NA>         <NA>
 4997   4dflow_v2      <NA>         <NA>

                                            source_table  \
 0     PESABrain_4DFlowv2_LocalizedTimeAvgFlow_202602...
 1     PESABrain_4DFlowv2_LocalizedTimeAvgFlow_202602...
 2     PESABrain_4DFlowv2_LocalizedTimeAvgFlow_202602...
 3     PESABrain_4DFlowv2_LocalizedTimeAvgFlow_202602...
 4     PESABrain_4DFlowv2_LocalizedTimeAvgFlow_202602...
 ...                                                 ...
 4993  PESABrain_4DFlowv2_LocalizedTimeAvgFlow_202602...
 4994  PESABrain_4DFlowv2_LocalizedTimeAvgFlow_202602...
 4995  PESABrain_4DFlowv2_LocalizedTimeAvgFlow_202602...
 4996  PESABrain_4DFlowv2_LocalizedTimeAvgFlow_202602...
 4997  PESABrain_4DFlowv2_LocalizedTimeAvgFlow_202602...

                                             source_file source_sheet  \
 0     PESABrain_4DFlowv2_LocalizedTimeAvgFlow_202602...       Sheet1
 1     PESABrain_4DFlowv2_LocalizedTimeAvgFlow_202602...       Sheet1
 2     PESABrain_4DFlowv2_LocalizedTimeAvgFlow_202602...       Sheet1
 3     PESABrain_4DFlowv2_LocalizedTimeAvgFlow_202602...       Sheet1
 4     PESABrain_4DFlowv2_LocalizedTimeAvgFlow_202602...       Sheet1
 ...                                                 ...          ...
 4993  PESABrain_4DFlowv2_LocalizedTimeAvgFlow_202602...       Sheet1
 4994  PESABrain_4DFlowv2_LocalizedTimeAvgFlow_202602...       Sheet1
 4995  PESABrain_4DFlowv2_LocalizedTimeAvgFlow_202602...       Sheet1
 4996  PESABrain_4DFlowv2_LocalizedTimeAvgFlow_202602...       Sheet1
 4997  PESABrain_4DFlowv2_LocalizedTimeAvgFlow_202602...       Sheet1

             source_column                 source_batch_id measured_at
 0              patient_id  pesabrain_20260411T194845+0000         NaT
 1              patient_id  pesabrain_20260411T194845+0000         NaT
 2              patient_id  pesabrain_20260411T194845+0000         NaT
 3              patient_id  pesabrain_20260411T194845+0000         NaT
 4              patient_id  pesabrain_20260411T194845+0000         NaT
 ...                   ...                             ...         ...
 4993  Right Communicating  pesabrain_20260411T194845+0000         NaT
 4994  Right Communicating  pesabrain_20260411T194845+0000         NaT
 4995  Right Communicating  pesabrain_20260411T194845+0000         NaT
 4996  Right Communicating  pesabrain_20260411T194845+0000         NaT
 4997  Right Communicating  pesabrain_20260411T194845+0000         NaT

 [4998 rows x 21 columns],
 'subjects':       subject_uid primary_patient_id primary_seqn     sex birth_date notes  \
 0         PESA841            PESA841           28    Male        NaT  <NA>
 1         PESA900            PESA900           29  Female        NaT  <NA>
 2        PESA3481           PESA3481           58    Male        NaT  <NA>
 3        PESA3600           PESA3600           59    Male        NaT  <NA>
 4        PESA4225           PESA4225           64  Female        NaT  <NA>
 ...           ...                ...          ...     ...        ...   ...
 1419  PESA9790641        PESA9790641          NaN     NaN        NaT  <NA>
 1420     PESA9801           PESA9801          NaN     NaN        NaT  <NA>
 1421   PESA986049         PESA986049          NaN     NaN        NaT  <NA>
 1422  PESA9884736        PESA9884736          NaN     NaN        NaT  <NA>
 1423   PESA996004         PESA996004          NaN     NaN        NaT  <NA>

        source_batch_id                 updated_at
 0     derived_subjects  2026-04-11T19:49:00+00:00
 1     derived_subjects  2026-04-11T19:49:00+00:00
 2     derived_subjects  2026-04-11T19:49:00+00:00
 3     derived_subjects  2026-04-11T19:49:00+00:00
 4     derived_subjects  2026-04-11T19:49:00+00:00
 ...                ...                        ...
 1419  derived_subjects  2026-04-11T19:49:18+00:00
 1420  derived_subjects  2026-04-11T19:49:18+00:00
 1421  derived_subjects  2026-04-11T19:49:18+00:00
 1422  derived_subjects  2026-04-11T19:49:18+00:00
 1423  derived_subjects  2026-04-11T19:49:18+00:00

 [1424 rows x 8 columns]}

In [ ]:
from nvitk.db import register_nifti_tree, upsert_nifti_assets, register_dicom_tree, upsert_dicom_assets


# upsert_nifti_assets(
#     repo,
#     "/data_local/LabVF/PESA-Brain/DATA/Nifti/",
#     source="local_nifti",
#     pipeline_id="raw",
# )

# upsert_dicom_assets(
#     repo,
#     "/home/imarcoss/NetVolumes/Tierra/LAB_VF-ICH/LAB/MCC LAB/_IgnacioMarcos/LabVF/PESA-Brain/DATA/DICOM/",
#     source="local_dicom",
#     pipeline_id="raw",
# )

In [4]:
# repo.drop_all_tables()

In [5]:
# repo.build_sqlite_index()

In [6]:
# repo.get("source_tables").sort_values(["source_file", "source_sheet", "source_kind"])

In [7]:
repo.clinical(
    variables=["BPXSYM", "BMI", "tacsctot_group"],
    filters={
        # "subject_uid": ["PESA10407076", "PESA16016004"],
        # "bmi": {"$ge": 27, "$lt": 30}
    },
    # wide=True,
)

       subject_uid visit_id        bmi bpxsym tacsctot_group
0     PESA10017225        4  30.119402  130.0             g1
1       PESA100489        4  22.662709  128.0             g0
2     PESA10048900        4        NaN  150.0             g1
3     PESA10055241        4  27.398176  117.0             g1
4      PESA1006009        4  27.968016  124.0             g0
...            ...      ...        ...    ...            ...
996    PESA9928801        4  27.041644  104.0             g0
997    PESA9935104        4  19.896194  122.0             g0
998    PESA9947716        4  29.757785  114.0             g1
999    PESA9954025        4  23.875659  126.0             g1
1000   PESA9972964        4  19.322185  109.0             g0

[1001 rows x 5 columns]

In [4]:
repo.get("image_measurements", filters={"modality": "4dflow", "pipeline_id": "4dflow_v2"}, wide=True)

,subject_uid,session_id,basi_flow_tseries,basi_flow_tseries_f1,basi_flow_tseries_f10,basi_flow_tseries_f11,basi_flow_tseries_f12,basi_flow_tseries_f13,basi_flow_tseries_f14,basi_flow_tseries_f2,...,unknown_right_mca_pi,unknown_right_pca,unknown_right_pca_pi,unknown_right_transverse,unknown_right_transverse_pi,unknown_sagital_sinus,unknown_sagital_sinus_pi,unknown_straight_sinus,unknown_straight_sinus_pi,unknown_tcbf
0,PESA1006009,,236.273289,222.314744,357.794466,339.262705,264.966946,259.840908,249.499483,209.365611,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,PESA1006009,BMRI923674,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.779952,80.300385,0.789376,19.333573,1.429554,323.031174,0.490242,NaN,NaN,989.379992
2,PESA10061584,,170.454354,158.902531,255.01688,195.198755,182.196264,195.871396,186.966147,165.393348,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,PESA10061584,BMRI287356,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.68358,57.542913,0.8117,NaN,NaN,205.061709,0.587768,NaN,NaN,592.901264
4,PESA10067929,,226.296816,220.646682,340.313301,317.290306,269.535484,266.557131,246.251392,210.764179,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
744,PESA9935104,BMRI881199,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.681599,83.574848,0.697529,338.670305,0.316357,32.164942,0.356296,307.330452,0.300294,797.586394
745,PESA9947716,,244.046602,239.164181,282.08416,296.94437,303.98037,289.510403,262.932816,217.07109,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
746,PESA9947716,BMRI447102,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.827749,145.011745,0.727097,449.154577,0.421292,400.318741,0.405469,NaN,NaN,1069.262393
747,PESA9972964,,271.334209,254.322996,328.669739,333.400555,299.912796,278.815441,281.728477,226.288948,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
748,PESA9972964,BMRI105334,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.771829,95.583015,0.857211,89.666714,0.550807,340.422518,0.436098,68.104586,0.378025,792.635572

In [6]:
repo.image(
    modality="4dflow",
    variables=["flow_mean", 'pi'],
    regions=["right_ica", "left_ica", 'basilar'],
    pipeline="4dflow_v1",
)

,subject_uid,session_id,basilar_flow_mean,basilar_pi,left_ica_flow_mean,left_ica_pi,right_ica_flow_mean,right_ica_pi
0,PESA1006009,BMRI923674,184.510389,0.791092,267.035802,0.701133,281.351906,0.727263
1,PESA10061584,BMRI287356,182.850943,0.819871,94.844843,0.639911,207.560577,0.698219
2,PESA10067929,BMRI965424,228.640571,0.810012,323.586469,0.773645,355.117301,0.796976
3,PESA10086976,BMRI859483,251.966084,0.657827,303.364359,0.540127,0.814246,0.847596
4,PESA10112400,BMRI465140,151.450536,0.657464,325.856177,0.707761,330.478438,0.791426
...,...,...,...,...,...,...,...,...
343,PESA9897316,BMRI994162,178.221377,0.674136,283.497145,0.709040,262.646432,0.782386
344,PESA9928801,BMRI487416,87.832792,0.567656,314.992869,0.850857,370.991649,0.870882
345,PESA9935104,BMRI881199,245.827435,0.719752,352.592480,0.753206,199.660541,0.735158
346,PESA9947716,BMRI447102,309.712580,0.857074,350.185589,0.807655,358.434131,0.811330
347,PESA9972964,BMRI105334,183.211070,0.688649,301.500929,0.668324,253.431541,0.742674

In [5]:
repo.image(
    modality="4dflow",
    variables=["flow_mean", 'pi'],
    regions=["right_ica", "left_ica", 'basilar'],
    # pipeline="4dflow_v2",
    # use_sqlite=False,
)

,subject_uid,session_id,basilar_flow_mean,basilar_pi,left_ica_flow_mean,left_ica_pi,right_ica_flow_mean,right_ica_pi
0,PESA1006009,BMRI923674,248.350620,0.789627,402.268053,0.749631,338.761318,0.769688
1,PESA10061584,BMRI287356,195.941298,0.806241,185.608497,0.724215,211.351469,0.885899
2,PESA10067929,BMRI965424,244.387905,0.658304,359.704287,0.654429,448.070589,0.798520
3,PESA10086976,BMRI859483,379.135876,0.698962,407.495483,0.527828,528.135244,0.639359
4,PESA10112400,BMRI465140,206.517756,0.688548,261.609664,0.689931,330.063474,0.699787
...,...,...,...,...,...,...,...,...
356,PESA9897316,BMRI994162,216.781694,0.755665,447.279219,0.713632,268.425630,0.707854
357,PESA9928801,BMRI487416,184.485604,0.589528,329.742618,0.685397,367.234387,0.865289
358,PESA9935104,BMRI881199,250.168143,0.736223,354.858458,0.758594,192.559793,0.725193
359,PESA9947716,BMRI447102,310.847985,0.811056,383.165075,0.894181,375.249332,0.754342
360,PESA9972964,BMRI105334,246.836039,0.604851,248.110076,0.735543,297.689458,0.666450

In [15]:
repo.image(
    modality="4dflow",
    # pipeline="pesabrain_4dflow_current",
    variables=["flow_tseries"],
    regions=["right_ica", "left_ica", 'basi'],
    wide=True,
    use_sqlite=True,
)

,subject_uid,session_id,basi,basi_f1,basi_f10,basi_f11,basi_f12,basi_f13,basi_f14,basi_f2,basi_f3,basi_f4,basi_f5,basi_f6,basi_f7,basi_f8,basi_f9
0,PESA1006009,,236.273289,222.314744,357.794466,339.262705,264.966946,259.840908,249.499483,209.365611,192.168431,175.530653,161.690140,170.108356,200.524592,338.046970,347.872009
1,PESA10061584,,170.454354,158.902531,255.016880,195.198755,182.196264,195.871396,186.966147,165.393348,144.243164,137.203560,129.619374,179.132624,276.093836,287.595320,275.231924
2,PESA10067929,,226.296816,220.646682,340.313301,317.290306,269.535484,266.557131,246.251392,210.764179,201.532774,181.186538,182.512965,179.431858,198.438535,295.326290,329.734325
3,PESA10086976,,316.401587,277.023497,374.315729,370.069427,367.002354,342.883759,323.298254,253.107948,292.247972,404.748974,463.293743,503.656540,518.109684,458.126793,422.751875
4,PESA10112400,,195.226722,187.510400,282.618341,262.028246,211.312995,213.823786,206.666265,163.197184,163.858080,155.557852,144.697738,148.059039,191.587644,284.726915,286.895142
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
356,PESA9897316,,175.868540,169.281464,235.169163,215.214186,208.740234,210.629196,183.629837,155.164304,155.025415,141.102676,212.675900,283.289394,297.846851,304.917097,303.171158
357,PESA9928801,,163.238053,170.131516,226.737299,224.118562,180.370960,190.752411,191.078167,161.831002,146.724558,141.885839,139.802098,166.742578,193.205466,248.561468,238.184667
358,PESA9935104,,249.962597,218.321028,345.393162,338.004627,295.715218,270.104742,264.635839,192.752423,188.243322,181.386523,171.546350,161.213593,225.498261,317.003603,332.740860
359,PESA9947716,,244.046602,239.164181,282.084160,296.944370,303.980370,289.510403,262.932816,217.071090,203.463192,277.944145,455.578279,444.939365,419.935570,382.175503,342.949734
360,PESA9972964,,271.334209,254.322996,328.669739,333.400555,299.912796,278.815441,281.728477,226.288948,211.503410,203.735476,185.449419,187.921844,184.101548,187.509613,267.846107

In [17]:
repo.image(
    modality="4dflow",
    # pipeline="pesabrain_4dflow_current",
    variables=["flow_tseries"],
    regions=["right_ica", "left_ica", 'basi'],
    pipeline="4dflow_v1",
    wide=True,
    use_sqlite=True,
)

,subject_uid,session_id,basi,basi_f1,basi_f10,basi_f11,basi_f12,basi_f13,basi_f14,basi_f2,basi_f3,basi_f4,basi_f5,basi_f6,basi_f7,basi_f8,basi_f9
0,PESA1006009,,171.740742,168.193645,262.681961,237.725158,188.848443,191.011362,189.220390,152.294641,138.217177,136.751847,130.361080,120.433002,160.840273,252.938347,266.397772
1,PESA10061584,,167.251668,155.436301,251.961823,186.144733,178.125043,174.001665,166.416178,151.897402,130.579791,123.068390,117.425623,159.254665,256.388626,267.339821,257.472410
2,PESA10067929,,234.015326,209.301810,331.168985,309.251060,264.493818,242.809982,229.040794,190.483975,179.451871,173.877940,162.381248,145.967445,177.177801,264.656296,315.530205
3,PESA10086976,,200.100117,181.868849,237.502127,246.950941,232.032981,216.727839,218.705420,175.903559,195.263457,289.014559,323.399076,341.653547,332.864256,311.874561,275.629978
4,PESA10112400,,139.311733,126.335349,205.431976,183.801470,159.936533,156.501975,155.314536,122.262626,115.729229,114.442914,112.360876,114.743800,146.442618,207.208228,211.934180
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
337,PESA9897316,,146.445465,146.135516,189.702344,170.771270,172.337880,168.572130,159.571881,138.917656,132.200232,127.832479,170.140100,240.659351,236.923871,247.977991,225.132494
338,PESA9928801,,78.387072,73.397763,118.553166,109.357817,90.608840,91.994212,86.635509,71.107993,69.733021,69.948456,68.694377,70.771401,97.363837,114.649208,114.833064
339,PESA9935104,,229.139428,203.757019,351.813755,317.140303,256.308432,260.468359,243.036089,207.432761,199.516983,187.837157,174.878869,180.644660,228.866200,321.558523,325.012980
340,PESA9947716,,253.525257,221.942196,273.990383,287.376165,289.021425,284.843245,276.262808,203.814025,199.518857,273.705168,464.965525,454.760971,426.791239,386.633577,348.537855
341,PESA9972964,,197.611041,180.883598,245.183058,252.565899,241.381731,212.511535,210.013647,169.744234,160.409818,147.973294,139.340687,129.881787,132.475276,126.397777,201.792669

In [12]:
repo.image(
    modality="asl",
    variables=['mean_cbf'],
    # regions=["right_ica"],
    atlas="desikan",
    wide=True,
    use_sqlite=True,
)

,subject_uid,session_id,ctx_left_anterior_cingulate,ctx_left_frontal_lobe,ctx_left_hemisphere,ctx_left_occipital_lobe,ctx_left_parietal_lobe,ctx_left_temporal_lobe,ctx_lh_bankssts,ctx_lh_caudalanteriorcingulate,...,ctx_rh_supramarginal,ctx_rh_temporalpole,ctx_rh_transversetemporal,ctx_right_anterior_cingulate,ctx_right_frontal_lobe,ctx_right_hemisphere,ctx_right_occipital_lobe,ctx_right_parietal_lobe,ctx_right_temporal_lobe,ctx_whole_brain
0,PESA10017225,BMRI613225,64.108216,65.458659,61.897253,56.170527,62.396216,56.541516,64.038344,67.557323,...,65.805750,52.896903,94.734164,70.327429,66.677251,62.871607,57.386706,62.975389,57.127302,62.389454
1,PESA1002001,IA706156,58.723609,52.989686,55.773419,60.135660,56.405732,54.849913,87.514262,67.551766,...,58.937474,55.399962,86.935706,58.474634,54.133276,55.731381,57.767403,56.196220,54.906978,55.751993
2,PESA100489,BMRI649274,87.214877,76.428488,73.555987,68.583159,68.530902,71.110262,72.251565,102.378239,...,85.157223,53.573930,123.434005,89.153019,78.027298,73.559161,65.177234,70.570929,69.668548,73.557550
3,PESA10055241,BMRI872431,57.442981,58.200862,55.306647,48.994470,55.218977,50.945834,64.805005,65.584888,...,59.737115,39.929875,85.994163,54.434933,57.211294,54.878386,48.371067,55.735338,51.788467,55.091414
4,PESA1006009,BMRI923674,68.255060,61.740562,63.393821,68.494657,65.866269,55.974345,65.231328,87.196869,...,66.337672,63.197503,101.617334,71.187907,67.408806,66.288385,69.423112,66.219254,59.196456,64.850706
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1378,PESA9935104,BMRI881199,55.811071,61.096123,57.807313,49.279588,60.576383,52.312585,62.371022,57.817307,...,60.765123,42.351298,94.461272,59.523966,59.512227,55.979328,49.214372,57.947922,50.774988,56.903359
1379,PESA9947716,BMRI447102,71.170601,74.731206,69.965742,60.644756,70.948384,62.829321,88.761006,83.577222,...,81.980738,54.961856,121.530419,82.271338,81.009304,74.834474,64.227081,74.830753,66.725016,72.428656
1380,PESA9954025,BMRI971103,65.226978,60.358033,59.377463,60.964903,58.965748,55.114155,62.779410,75.575217,...,65.520952,44.724364,112.838517,69.849831,61.292834,59.850783,58.694509,58.779466,55.479826,59.616568
1381,PESA996004,IA192427,45.505831,39.947504,41.080146,38.991172,40.303477,42.355687,44.566342,48.221394,...,39.586373,48.949522,83.811986,40.148030,34.785846,37.419248,33.302293,37.361973,40.334107,39.217882
1382,PESA9972964,BMRI105334,60.014801,64.614286,61.776127,53.121316,65.587765,56.777678,56.897966,70.174414,...,67.255690,46.138130,103.784023,59.201978,65.579722,62.464305,53.374576,65.579486,57.195454,62.120475

In [8]:
clinical = repo.clinical(
    variables=["BPXSYM", "BMI", "tacsctot_group"],
    filters={"subject_uid": ["PESA10407076", "PESA16016004"]},
    wide=True,
)

hemo = repo.image(
    modality="4dflow",
    variables=["flow_mean", 'pi'],
    regions=["right_ica", "left_ica"],
    pipeline="legacy",
    wide=True,
)

report_df = repo.join([clinical, hemo])
report_df.head()

,subject_uid,visit_id,bmi,bpxsym,tacsctot_group,session_id,left_ica_flow_mean,left_ica_pi,right_ica_flow_mean,right_ica_pi
0,PESA10407076,4,29.011226,137.0,g1,BMRI395267,336.984932,0.698981,346.493410,0.719224
1,PESA16016004,4,25.099502,121.0,g1,BMRI611724,438.522579,0.929726,397.337101,0.939473

In [27]:
# repo.build_sqlite_index()

PosixPath('/home/imarcoss/nvitk/dataset/cache/index.sqlite')

In [ ]:
# import_pesabrain_source(
#     repo,
#     db_base,
#     "PESABrain_ASLPerfusion_CovCBF_20260216.xlsx",
#     sheet="Sheet1",
#     source_kind="image_wide",
# )

repo.image(
    modality="asl",
    variables=["cov_cbf"],
    atlas="desikan",
    wide=True,
)

,subject_uid,session_id,asl__ctx_left_anterior_cingulate__cov_cbf,asl__ctx_left_frontal_lobe__cov_cbf,asl__ctx_left_hemisphere__cov_cbf,asl__ctx_left_occipital_lobe__cov_cbf,asl__ctx_left_parietal_lobe__cov_cbf,asl__ctx_left_temporal_lobe__cov_cbf,asl__ctx_lh_bankssts__cov_cbf,asl__ctx_lh_caudalanteriorcingulate__cov_cbf,...,asl__ctx_rh_supramarginal__cov_cbf,asl__ctx_rh_temporalpole__cov_cbf,asl__ctx_rh_transversetemporal__cov_cbf,asl__ctx_right_anterior_cingulate__cov_cbf,asl__ctx_right_frontal_lobe__cov_cbf,asl__ctx_right_hemisphere__cov_cbf,asl__ctx_right_occipital_lobe__cov_cbf,asl__ctx_right_parietal_lobe__cov_cbf,asl__ctx_right_temporal_lobe__cov_cbf,asl__ctx_whole_brain__cov_cbf
0,PESA10017225,BMRI613225,0.452060,0.472829,0.560015,0.620081,0.590010,0.651455,0.542885,0.287351,...,0.501129,0.579615,0.374256,0.390560,0.464650,0.557169,0.600517,0.584465,0.681216,0.558625
1,PESA1002001,IA706156,0.395617,0.544135,0.611366,0.576589,0.639490,0.700544,0.587060,0.353848,...,0.552336,0.528527,0.370642,0.406422,0.525181,0.583345,0.574381,0.639043,0.626311,0.597330
2,PESA100489,BMRI649274,0.527712,0.543879,0.643825,0.682902,0.716763,0.722049,0.778027,0.402595,...,0.504942,0.607363,0.392171,0.490312,0.534953,0.636887,0.726292,0.683077,0.726770,0.640423
3,PESA10055241,BMRI872431,0.426895,0.448705,0.553270,0.661140,0.557523,0.694156,0.601335,0.287250,...,0.424982,0.799478,0.355929,0.388077,0.439817,0.533953,0.620370,0.546580,0.650340,0.543731
4,PESA1006009,BMRI923674,0.518955,0.533282,0.563952,0.551462,0.546076,0.660492,0.500050,0.318890,...,0.492034,0.734295,0.321753,0.464139,0.502499,0.548704,0.561752,0.525568,0.662551,0.556577
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1378,PESA9935104,BMRI881199,0.405067,0.473152,0.518197,0.564974,0.534482,0.557154,0.507536,0.371898,...,0.460791,0.549321,0.170726,0.396846,0.494713,0.556186,0.591173,0.569271,0.638182,0.537029
1379,PESA9947716,BMRI447102,0.381084,0.456018,0.570185,0.597395,0.618159,0.685539,0.589018,0.299786,...,0.457169,0.472424,0.316467,0.300117,0.456946,0.560157,0.573520,0.601857,0.688001,0.566396
1380,PESA9954025,BMRI971103,0.472588,0.493494,0.565424,0.604163,0.582947,0.666161,0.568104,0.302939,...,0.495543,0.600872,0.289030,0.422153,0.484560,0.545574,0.553304,0.561335,0.636993,0.555460
1381,PESA996004,IA192427,0.827544,0.663378,0.722074,0.682393,0.694752,0.808883,0.643079,0.571278,...,0.585958,0.580459,0.434666,0.588588,0.636693,0.722169,0.655451,0.723059,0.810111,0.724639
1382,PESA9972964,BMRI105334,0.408378,0.504800,0.579825,0.648434,0.597248,0.674092,0.600755,0.306917,...,0.555574,0.599855,0.337562,0.384505,0.499499,0.566991,0.593799,0.574100,0.671367,0.573412

In [ ]:
from nvitk.db import register_nifti_tree, upsert_nifti_assets, register_dicom_tree, upsert_dicom_assets

# DataFrame only (no write)
df = register_nifti_tree(
    "/data_local/LabVF/PESA-Brain/DATA/Nifti/",
    source="local_nifti",
    pipeline_id="raw",
)
df

,asset_uid,subject_uid,session_uid,modality,asset_type,asset_path,resource_label,source,pipeline_name,pipeline_id,exists_locally,asset_slot,metadata_json,source_batch_id,updated_at
0,local:PESA10758400:tof:PESA10758400/TOF/BMRI60...,PESA10758400,<NA>,tof,nifti,/data_local/LabVF/PESA-Brain/DATA/Nifti/PESA10...,TOF,local_nifti,<NA>,raw,True,tof,"{""relative_path"": ""PESA10758400/TOF/BMRI607930...",local_nifti_20260411T150223+0000,2026-04-11T15:02:23+00:00
1,local:PESA10758400:4dflow:PESA10758400/4DFlow/...,PESA10758400,<NA>,4dflow,nifti,/data_local/LabVF/PESA-Brain/DATA/Nifti/PESA10...,4DFlow/AP,local_nifti,<NA>,raw,True,flow_ap_m,"{""relative_path"": ""PESA10758400/4DFlow/AP/BMRI...",local_nifti_20260411T150223+0000,2026-04-11T15:02:23+00:00
2,local:PESA10758400:4dflow:PESA10758400/4DFlow/...,PESA10758400,<NA>,4dflow,nifti,/data_local/LabVF/PESA-Brain/DATA/Nifti/PESA10...,4DFlow/AP,local_nifti,<NA>,raw,True,flow_ap_ph,"{""relative_path"": ""PESA10758400/4DFlow/AP/BMRI...",local_nifti_20260411T150223+0000,2026-04-11T15:02:23+00:00
3,local:PESA10758400:4dflow:PESA10758400/4DFlow/...,PESA10758400,<NA>,4dflow,nifti,/data_local/LabVF/PESA-Brain/DATA/Nifti/PESA10...,4DFlow,local_nifti,<NA>,raw,True,flow_angiography_3d,"{""relative_path"": ""PESA10758400/4DFlow/Angiogr...",local_nifti_20260411T150223+0000,2026-04-11T15:02:23+00:00
4,local:PESA10758400:4dflow:PESA10758400/4DFlow/...,PESA10758400,<NA>,4dflow,nifti,/data_local/LabVF/PESA-Brain/DATA/Nifti/PESA10...,4DFlow,local_nifti,<NA>,raw,True,flow_angiography_4d,"{""relative_path"": ""PESA10758400/4DFlow/Angiogr...",local_nifti_20260411T150223+0000,2026-04-11T15:02:23+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142,local:PESA9541921:4dflow:PESA9541921/4DFlow/PC...,PESA9541921,<NA>,4dflow,nifti,/data_local/LabVF/PESA-Brain/DATA/Nifti/PESA95...,4DFlow,local_nifti,<NA>,raw,True,NaN,"{""relative_path"": ""PESA9541921/4DFlow/PCMRA_no...",local_nifti_20260411T150223+0000,2026-04-11T15:02:23+00:00
143,local:PESA9541921:4dflow:PESA9541921/4DFlow/RL...,PESA9541921,<NA>,4dflow,nifti,/data_local/LabVF/PESA-Brain/DATA/Nifti/PESA95...,4DFlow/RL,local_nifti,<NA>,raw,True,flow_rl_m,"{""relative_path"": ""PESA9541921/4DFlow/RL/BMRI6...",local_nifti_20260411T150223+0000,2026-04-11T15:02:23+00:00
144,local:PESA9541921:4dflow:PESA9541921/4DFlow/RL...,PESA9541921,<NA>,4dflow,nifti,/data_local/LabVF/PESA-Brain/DATA/Nifti/PESA95...,4DFlow/RL,local_nifti,<NA>,raw,True,flow_rl_ph,"{""relative_path"": ""PESA9541921/4DFlow/RL/BMRI6...",local_nifti_20260411T150223+0000,2026-04-11T15:02:23+00:00
145,local:PESA9541921:4dflow:PESA9541921/4DFlow/Ve...,PESA9541921,<NA>,4dflow,nifti,/data_local/LabVF/PESA-Brain/DATA/Nifti/PESA95...,4DFlow,local_nifti,<NA>,raw,True,flow_velocity_magnitude_3d,"{""relative_path"": ""PESA9541921/4DFlow/Velocity...",local_nifti_20260411T150223+0000,2026-04-11T15:02:23+00:00
146,local:PESA9541921:4dflow:PESA9541921/4DFlow/Ve...,PESA9541921,<NA>,4dflow,nifti,/data_local/LabVF/PESA-Brain/DATA/Nifti/PESA95...,4DFlow,local_nifti,<NA>,raw,True,flow_velocity_magnitude_4d,"{""relative_path"": ""PESA9541921/4DFlow/Velocity...",local_nifti_20260411T150223+0000,2026-04-11T15:02:23+00:00

In [ ]:
df = register_dicom_tree(
    "/home/imarcoss/NetVolumes/Tierra/LAB_VF-ICH/LAB/MCC LAB/_IgnacioMarcos/LabVF/PESA-Brain/DATA/DICOM/",
    source="local_dicom",
    pipeline_id="raw",
)
df

In [ ]:

# # Write into dataset Parquet + optional SQLite index
upsert_dicom_assets(
    repo,
    "/home/imarcoss/NetVolumes/Tierra/LAB_VF-ICH/LAB/MCC LAB/_IgnacioMarcos/LabVF/PESA-Brain/DATA/DICOM/",
    source="local_dicom",
    pipeline_id="raw",
)

# upsert_nifti_assets(
#     repo,
#     "/data_local/LabVF/PESA-Brain/DATA/Nifti/",
#     source="local_nifti",
#     pipeline_id="raw",
# )

,asset_uid,subject_uid,session_uid,modality,asset_type,asset_path,resource_label,source,pipeline_name,pipeline_id,exists_locally,asset_slot,metadata_json,source_batch_id,updated_at
0,local:PESA10758400:tof:PESA10758400/TOF/BMRI60...,PESA10758400,<NA>,tof,nifti,/data_local/LabVF/PESA-Brain/DATA/Nifti/PESA10...,TOF,local_nifti,<NA>,raw,True,tof,"{""relative_path"": ""PESA10758400/TOF/BMRI607930...",local_nifti_20260411T150248+0000,2026-04-11T15:02:48+00:00
1,local:PESA10758400:4dflow:PESA10758400/4DFlow/...,PESA10758400,<NA>,4dflow,nifti,/data_local/LabVF/PESA-Brain/DATA/Nifti/PESA10...,4DFlow/AP,local_nifti,<NA>,raw,True,flow_ap_m,"{""relative_path"": ""PESA10758400/4DFlow/AP/BMRI...",local_nifti_20260411T150248+0000,2026-04-11T15:02:48+00:00
2,local:PESA10758400:4dflow:PESA10758400/4DFlow/...,PESA10758400,<NA>,4dflow,nifti,/data_local/LabVF/PESA-Brain/DATA/Nifti/PESA10...,4DFlow/AP,local_nifti,<NA>,raw,True,flow_ap_ph,"{""relative_path"": ""PESA10758400/4DFlow/AP/BMRI...",local_nifti_20260411T150248+0000,2026-04-11T15:02:48+00:00
3,local:PESA10758400:4dflow:PESA10758400/4DFlow/...,PESA10758400,<NA>,4dflow,nifti,/data_local/LabVF/PESA-Brain/DATA/Nifti/PESA10...,4DFlow,local_nifti,<NA>,raw,True,flow_angiography_3d,"{""relative_path"": ""PESA10758400/4DFlow/Angiogr...",local_nifti_20260411T150248+0000,2026-04-11T15:02:48+00:00
4,local:PESA10758400:4dflow:PESA10758400/4DFlow/...,PESA10758400,<NA>,4dflow,nifti,/data_local/LabVF/PESA-Brain/DATA/Nifti/PESA10...,4DFlow,local_nifti,<NA>,raw,True,flow_angiography_4d,"{""relative_path"": ""PESA10758400/4DFlow/Angiogr...",local_nifti_20260411T150248+0000,2026-04-11T15:02:48+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142,local:PESA9541921:4dflow:PESA9541921/4DFlow/PC...,PESA9541921,<NA>,4dflow,nifti,/data_local/LabVF/PESA-Brain/DATA/Nifti/PESA95...,4DFlow,local_nifti,<NA>,raw,True,NaN,"{""relative_path"": ""PESA9541921/4DFlow/PCMRA_no...",local_nifti_20260411T150248+0000,2026-04-11T15:02:48+00:00
143,local:PESA9541921:4dflow:PESA9541921/4DFlow/RL...,PESA9541921,<NA>,4dflow,nifti,/data_local/LabVF/PESA-Brain/DATA/Nifti/PESA95...,4DFlow/RL,local_nifti,<NA>,raw,True,flow_rl_m,"{""relative_path"": ""PESA9541921/4DFlow/RL/BMRI6...",local_nifti_20260411T150248+0000,2026-04-11T15:02:48+00:00
144,local:PESA9541921:4dflow:PESA9541921/4DFlow/RL...,PESA9541921,<NA>,4dflow,nifti,/data_local/LabVF/PESA-Brain/DATA/Nifti/PESA95...,4DFlow/RL,local_nifti,<NA>,raw,True,flow_rl_ph,"{""relative_path"": ""PESA9541921/4DFlow/RL/BMRI6...",local_nifti_20260411T150248+0000,2026-04-11T15:02:48+00:00
145,local:PESA9541921:4dflow:PESA9541921/4DFlow/Ve...,PESA9541921,<NA>,4dflow,nifti,/data_local/LabVF/PESA-Brain/DATA/Nifti/PESA95...,4DFlow,local_nifti,<NA>,raw,True,flow_velocity_magnitude_3d,"{""relative_path"": ""PESA9541921/4DFlow/Velocity...",local_nifti_20260411T150248+0000,2026-04-11T15:02:48+00:00
146,local:PESA9541921:4dflow:PESA9541921/4DFlow/Ve...,PESA9541921,<NA>,4dflow,nifti,/data_local/LabVF/PESA-Brain/DATA/Nifti/PESA95...,4DFlow,local_nifti,<NA>,raw,True,flow_velocity_magnitude_4d,"{""relative_path"": ""PESA9541921/4DFlow/Velocity...",local_nifti_20260411T150248+0000,2026-04-11T15:02:48+00:00

In [ ]:
res = repo.assets(filters={"asset_type": "nifti", 'subject_uid': 'PESA10758400', 'modality': 'tof'})
tof = nv.imread(res.asset_path.iloc[0])
print(tof)

Image(shape=(800, 800, 180), dtype=float64, backend=cupy, axes='XYZ', name='BMRI607930_cs3DI_MC_1601', modality='MR', submodality=None, rescale_type='DV')

In [ ]:
res = repo.assets(filters={"asset_type": "nifti", 'subject_uid': 'PESA10758400', 'modality': '4dflow'})
flow_ap_ph = nv.imread(res.asset_path[res.asset_slot == 'flow_ap_ph'].iloc[0])
print(flow_ap_ph)

Image(shape=(256, 256, 101, 15), dtype=float64, backend=cupy, axes='XYZT', name='BMRI607930_4DQflowNeuro_AP_2003_ph', modality='MR', submodality=None, rescale_type='DV')

In [ ]:
res = repo.assets(filters={"asset_type": "nifti"})

print(pd.unique(res["subject_uid"]))
print(pd.unique(res["modality"]))

<ArrowStringArray>
['PESA10758400', 'PESA11937025', 'PESA12517444', 'PESA15792676',
 'PESA15808576',  'PESA2196324',  'PESA5745609',  'PESA6160324',
  'PESA8404201',  'PESA8856576',  'PESA9541921']
Length: 11, dtype: string
<ArrowStringArray>
['tof', '4dflow']
Length: 2, dtype: string

In [ ]:
# # Wide assets: one row per subject; columns are asset_slot (e.g. flow_ap_m). Long form uses assets(wide=False).
# wide_assets = repo.asset(filters={"asset_type": "nifti", "subject_uid": "PESA10758400"})
# assert "flow_ap_m" in wide_assets.columns
# long_assets = repo.assets(wide=False, filters={"asset_type": "nifti", "modality": "4dflow", "subject_uid": "PESA10758400"})
# assert "asset_slot" in long_assets.columns
# wide_assets.filter(regex="^flow_").iloc[0, :4]

In [ ]:
# Remove

# empty = repo.get("subject_ids").iloc[0:0]
# repo.write_table("subject_ids", empty, provenance={"importer": "undo batch {trial_id}"})

# empty = repo.get("clinical_measurements").iloc[0:0]
# repo.write_table("clinical_measurements", empty, provenance={"importer": "undo batch {trial_id}"})

# empty = repo.get("image_measurements").iloc[0:0]
# repo.write_table("image_measurements", empty, provenance={"importer": "undo batch {trial_id}"})

# src = repo.get("source_tables")
# src = src[src["source_batch_id"] != trial_id]
# repo.write_table(
#   "source_tables",
#   src,
#   provenance={"reason": f"undo batch {trial_id}"},
# )

PosixPath('/home/imarcoss/nvitk/notebooks/prototypes/dataset/tables/image_measurements.parquet')