In [2]:
import os
import sys
from pathlib import Path
import pandas as pd

ROOT = Path(os.path.abspath('')).resolve().parents[2]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))


import nvitk as nv

from nvitk import db
from nvitk.db import DataRepo, import_pesabrain_source
from nvitk.db import upsert_nifti_assets, upsert_dicom_assets, register_nifti_tree, register_dicom_tree
from nvitk.db.repo import DataRepo
from nvitk.db.xnat import XnatConnectionConfig, sync_xnat_project
from nvitk.db import get_repo_from_settings

In [6]:
# !python test/prototypes/db/import_new_vars.py --dataset-root ~/nvitk/dataset/nvitk-dataset/ --build-sqlite-index

repo = DataRepo('~/nvitk/dataset/nvitk-dataset', auto_scaffold=True, use_sqlite=True)
import_pesabrain_source(
    repo,
    "/data_local/LabVF/PESA-Brain/DB/new_vars",
    "PESABrain_ASLPerfusion_VascularAtlas_MeanATT_20260216.xlsx",
    pipeline_id='asl_v1',
    build_sqlite_index=True,    
)

import_pesabrain_source(
    repo,
    "/data_local/LabVF/PESA-Brain/DB/new_vars",
    "PESABrain_ASLPerfusion_VascularAtlas_MedianATT_20260216.xlsx",
    pipeline_id='asl_v1',
    build_sqlite_index=True,
)

{'filename': 'PESABrain_ASLPerfusion_VascularAtlas_MedianATT_20260216.xlsx',
 'sheet': 'Sheet1',
 'source_kind': 'image_wide',
 'cohort_id': 'PESA-Brain',
 'result':       subject_uid  session_id modality region_id region_label  frame_index  \
 0            <NA>  BMRI100102      asl      <NA>         <NA>         <NA>
 1            <NA>  BMRI101198      asl      <NA>         <NA>         <NA>
 2            <NA>  BMRI101846      asl      <NA>         <NA>         <NA>
 3            <NA>  BMRI103891      asl      <NA>         <NA>         <NA>
 4            <NA>  BMRI104117      asl      <NA>         <NA>         <NA>
 ...           ...         ...      ...       ...          ...          ...
 24781        <NA>    IA969203      asl      <NA>         <NA>         <NA>
 24782        <NA>    IA986829      asl      <NA>         <NA>         <NA>
 24783        <NA>    IA991610      asl      <NA>         <NA>         <NA>
 24784        <NA>    IA992548      asl      <NA>         <NA>         <NA>
 24785        <NA>    IA997088      asl      <NA>         <NA>         <NA>

        variable_id  value_num value_text  unit  ...  \
 0       left_aca_0   1.320618       <NA>  <NA>  ...
 1       left_aca_0   1.217214       <NA>  <NA>  ...
 2       left_aca_0   1.216720       <NA>  <NA>  ...
 3       left_aca_0   1.193104       <NA>  <NA>  ...
 4       left_aca_0   1.244488       <NA>  <NA>  ...
 ...            ...        ...        ...   ...  ...
 24781  watershed_8   1.261407       <NA>  <NA>  ...
 24782  watershed_8   1.430709       <NA>  <NA>  ...
 24783  watershed_8   1.421652       <NA>  <NA>  ...
 24784  watershed_8   1.296723       <NA>  <NA>  ...
 24785  watershed_8   1.399787       <NA>  <NA>  ...

                                            pipeline_name pipeline_id  \
 0      PESABrain_ASLPerfusion_VascularAtlas_MedianATT...      asl_v1
 1      PESABrain_ASLPerfusion_VascularAtlas_MedianATT...      asl_v1
 2      PESABrain_ASLPerfusion_VascularAtlas_MedianATT...      asl_v1
 3      PESABrain_ASLPerfusion_VascularAtlas_MedianATT...      asl_v1
 4      PESABrain_ASLPerfusion_VascularAtlas_MedianATT...      asl_v1
 ...                                                  ...         ...
 24781  PESABrain_ASLPerfusion_VascularAtlas_MedianATT...      asl_v1
 24782  PESABrain_ASLPerfusion_VascularAtlas_MedianATT...      asl_v1
 24783  PESABrain_ASLPerfusion_VascularAtlas_MedianATT...      asl_v1
 24784  PESABrain_ASLPerfusion_VascularAtlas_MedianATT...      asl_v1
 24785  PESABrain_ASLPerfusion_VascularAtlas_MedianATT...      asl_v1

       qc_status source_asset  \
 0          <NA>         <NA>
 1          <NA>         <NA>
 2          <NA>         <NA>
 3          <NA>         <NA>
 4          <NA>         <NA>
 ...         ...          ...
 24781      <NA>         <NA>
 24782      <NA>         <NA>
 24783      <NA>         <NA>
 24784      <NA>         <NA>
 24785      <NA>         <NA>

                                             source_table  \
 0      PESABrain_ASLPerfusion_VascularAtlas_MedianATT...
 1      PESABrain_ASLPerfusion_VascularAtlas_MedianATT...
 2      PESABrain_ASLPerfusion_VascularAtlas_MedianATT...
 3      PESABrain_ASLPerfusion_VascularAtlas_MedianATT...
 4      PESABrain_ASLPerfusion_VascularAtlas_MedianATT...
 ...                                                  ...
 24781  PESABrain_ASLPerfusion_VascularAtlas_MedianATT...
 24782  PESABrain_ASLPerfusion_VascularAtlas_MedianATT...
 24783  PESABrain_ASLPerfusion_VascularAtlas_MedianATT...
 24784  PESABrain_ASLPerfusion_VascularAtlas_MedianATT...
 24785  PESABrain_ASLPerfusion_VascularAtlas_MedianATT...

                                              source_file source_sheet  \
 0      PESABrain_ASLPerfusion_VascularAtlas_MedianATT...       Sheet1
 1      PESABrain_ASLPerfusion_VascularAtlas_MedianATT...       Sheet1
 2      PESABrain_ASLPerfusion_VascularAtlas_MedianATT...       Sheet1
 3      PESABrain_ASLPerfusion_VascularAtlas_MedianATT...       Sheet1
 4      PESABrain_ASLPerfusion_VascularAtlas_MedianATT...       Sheet1
 ...                                                  ...          ...
 24781  PESABrain_ASLPerfusion_VascularAtlas_MedianATT...       Sheet1
 24782  PESABrain_ASLPerfusion_VascularAtlas_MedianATT...       Sheet1
 24783  PESABrain_ASLPerfusion_VascularAtlas_MedianATT...       Sheet1
 24784  PESABrain_ASLPerfusion_VascularAtlas_MedianATT...       Sheet1
 24785  PESABrain_ASLPerfusion_VascularAtlas_MedianATT...       Sheet1

       source_column                 source_batch_id measured_at
 0        Left_ACA-0  pesabrain_20260417T104805+0000         NaT
 1        Left_ACA-0  pesabrain_20260417T104805+0000         NaT
 2        Left_ACA-0  pesabrain_20260417T104805+0000         NaT
 3        Left_ACA-0  pesabrain_20260417T104805+0000         NaT
 4        Left_ACA-0  pesabrain_20260417T104805+0000         NaT
 ...             ...                             ...         ...
 24781   Watershed-8  pesabrain_20260417T104805+0000         NaT
 24782   Watershed-8  pesabrain_20260417T104805+0000         NaT
 24783   Watershed-8  pesabrain_20260417T104805+0000         NaT
 24784   Watershed-8  pesabrain_20260417T104805+0000         NaT
 24785   Watershed-8  pesabrain_20260417T104805+0000         NaT

 [24786 rows x 21 columns],
 'subjects':       subject_uid primary_patient_id primary_seqn     sex birth_date notes  \
 0         PESA841            PESA841           28    Male        NaT  <NA>
 1         PESA900            PESA900           29  Female        NaT  <NA>
 2        PESA3481           PESA3481           58    Male        NaT  <NA>
 3        PESA3600           PESA3600           59    Male        NaT  <NA>
 4        PESA4225           PESA4225           64  Female        NaT  <NA>
 ...           ...                ...          ...     ...        ...   ...
 1419     PESA9801           PESA9801           98     NaN        NaT  <NA>
 1420   PESA986049         PESA986049          992     NaN        NaT  <NA>
 1421  PESA9884736        PESA9884736         3143     NaN        NaT  <NA>
 1422   PESA996004         PESA996004          997     NaN        NaT  <NA>
 1423   PESA787624         PESA787624          NaN     NaN        NaT  <NA>

        source_batch_id                 updated_at
 0     derived_subjects  2026-04-17T10:48:35+00:00
 1     derived_subjects  2026-04-17T10:48:35+00:00
 2     derived_subjects  2026-04-17T10:48:35+00:00
 3     derived_subjects  2026-04-17T10:48:35+00:00
 4     derived_subjects  2026-04-17T10:48:35+00:00
 ...                ...                        ...
 1419  derived_subjects  2026-04-17T10:48:45+00:00
 1420  derived_subjects  2026-04-17T10:48:45+00:00
 1421  derived_subjects  2026-04-17T10:48:45+00:00
 1422  derived_subjects  2026-04-17T10:48:45+00:00
 1423  derived_subjects  2026-04-17T10:48:45+00:00

 [1424 rows x 8 columns]}

In [3]:
repo, xnat_config = get_repo_from_settings(return_xnat_config=True)

Using local root: ~/nvitk/dataset/nvitk-dataset

In [ ]:
repo.clinical(
    filters={"variable_id": ["bpxdim", "pp", 'bpxsym', 'pulse_pressure_map', 'apoe_group', 'apoe']},
)

Empty DataFrame
Columns: [subject_uid, modality, region_id, region_label, frame_index, variable_id, value_num, value_text, unit, value_kind, pipeline_name, pipeline_id, qc_status, source_asset, source_table, source_file, source_sheet, source_column, source_batch_id, measured_at, session_id, updated_at]
Index: []

[0 rows x 22 columns]

In [7]:
repo.image(
    modality="flair",
    variables=['wmh_dist', 'wmh_freq', 'wmh_les', 'wmh_reg']
)

,subject_uid,session_id,1_wmh_dist,1_wmh_freq,1_wmh_les,1_wmh_reg,2_wmh_dist,2_wmh_freq,2_wmh_les,2_wmh_reg,...,t_wmh_les,t_wmh_reg,tl_wmh_dist,tl_wmh_freq,tl_wmh_les,tl_wmh_reg,tr_wmh_dist,tr_wmh_freq,tr_wmh_les,tr_wmh_reg
0,PESA10017225,BMRI613225,0.320745,0.106074,2839.708513,26771.0,0.22162,0.032775,1962.101758,59866.0,...,1393.926699,115106.0,0.059321,0.009252,525.199466,56765.0,0.098123,0.014891,868.727233,58341.0
1,PESA100489,BMRI649274,0.295037,0.14012,3586.933487,25599.0,0.170668,0.035126,2074.909489,59071.0,...,1768.910992,123011.0,0.088005,0.017171,1069.929088,62312.0,0.057494,0.011516,698.981903,60699.0
2,PESA10055241,BMRI872431,0.580707,0.109367,2990.434142,27343.0,0.195301,0.017058,1005.731797,58958.0,...,889.905221,112233.0,0.080859,0.007641,416.393687,54493.0,0.09195,0.008201,473.511535,57740.0
3,PESA1006009,BMRI923674,0.399685,0.085393,1611.367201,18870.0,0.160635,0.012939,647.615519,50052.0,...,373.542055,104225.0,0.036069,0.002877,145.417255,50536.0,0.056584,0.004249,228.1248,53689.0
4,PESA10061584,BMRI287356,0.319367,0.02685,727.475864,27094.0,0.280982,0.010577,640.038536,60512.0,...,107.059194,117811.0,0.037943,0.001436,86.428205,60204.0,0.009057,0.000358,20.630989,57607.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
968,PESA9928801,BMRI487416,0.533885,0.052481,971.736903,18516.0,0.124276,0.004945,226.197829,45740.0,...,355.542384,92910.0,0.082011,0.003234,149.269458,46163.0,0.113329,0.004413,206.272926,46747.0
969,PESA9935104,BMRI881199,0.393805,0.032496,689.144976,21207.0,0.240798,0.00885,421.38811,47614.0,...,292.116036,100050.0,0.078873,0.002772,138.024824,49786.0,0.088054,0.003066,154.091211,50264.0
970,PESA9947716,BMRI447102,0.535515,0.080649,2119.787922,26284.0,0.126043,0.00869,498.928012,57413.0,...,589.57518,111511.0,0.08794,0.00644,348.103547,54055.0,0.061002,0.004203,241.471634,57456.0
971,PESA9954025,BMRI971103,0.407106,0.048519,1395.791544,28768.0,0.22159,0.011748,759.736372,64672.0,...,1152.374893,124869.0,0.146212,0.008055,501.297463,62235.0,0.189898,0.010395,651.07743,62634.0
972,PESA9972964,BMRI105334,0.590664,0.028772,616.582303,21452.0,0.142673,0.002977,148.933594,50115.0,...,125.780926,110410.0,0.061918,0.001183,64.634757,54635.0,0.058576,0.001096,61.146169,55775.0

In [9]:
repo.image(
    modality="t1",
    variables=['t1_cortical_volume']
)

,subject_uid,session_id,id,measurement,region,side,subject,value
0,PESA10017225,BMRI613225,CNIC_E01035,MeanCurv,superiorfrontal,right,PESA10017225,0.113
1,PESA1002001,IA706156,CNIC_E00484,MeanCurv,superiorparietal,right,PESA1002001,0.108
2,PESA100489,BMRI649274,CNIC_E00957,MeanCurv,superiorparietal,right,PESA100489,0.112
3,PESA10055241,BMRI872431,CNIC_E00903,CurvInd,temporalpole,left,PESA10055241,0.8
4,PESA1006009,BMRI923674,CNIC_E00301,MeanCurv,superiorparietal,right,PESA1006009,0.11
...,...,...,...,...,...,...,...,...
1377,PESA9935104,BMRI881199,CNIC_E00357,MeanCurv,superiorfrontal,right,PESA9935104,0.115
1378,PESA9947716,BMRI447102,CNIC_E00399,MeanCurv,superiortemporal,right,PESA9947716,0.101
1379,PESA9954025,BMRI971103,CNIC_E01530,MeanCurv,superiorparietal,right,PESA9954025,0.115
1380,PESA996004,IA192427,CNIC_E01220,MeanCurv,superiorfrontal,right,PESA996004,0.124
1381,PESA9972964,BMRI105334,CNIC_E00213,MeanCurv,superiorparietal,right,PESA9972964,0.123

In [10]:
pd.unique(repo.image(modality="t1",variables=['t1_cortical_volume']).measurement)

array(['MeanCurv', 'CurvInd', 'GrayVol', 'Volume_mm3', 'ThickStd',
       'GausCurv'], dtype=object)

In [11]:
repo.image(
    modality="asl",
    variables=['att_mean']
)

,subject_uid,session_id,3rd_ventricle,4th_ventricle,brain_stem,cc_anterior,cc_central,cc_mid_anterior,cc_mid_posterior,cc_posterior,...,right_choroid_plexus,right_hippocampus,right_inf_lat_vent,right_lateral_ventricle,right_pallidum,right_putamen,right_thalamus,right_ventraldc,right_vessel,wm_hypointensities
0,PESA10017225,BMRI613225,1.437767,1.225247,1.236855,1.135062,0.917922,0.964975,1.061468,1.183837,...,0.957197,1.116542,1.220047,1.326181,1.033393,0.969021,1.221106,1.204374,NaN,1.333060
1,PESA1002001,IA706156,1.323019,1.264247,1.243192,1.190722,0.961365,0.929321,1.028651,1.231656,...,1.182886,1.096770,1.341399,1.349049,1.209011,1.091082,1.276714,1.209576,NaN,1.328825
2,PESA100489,BMRI649274,1.324065,1.261800,1.267750,1.238174,1.096475,0.880688,1.076357,1.367370,...,1.262841,1.114299,1.079646,1.368322,1.118256,1.042300,1.361830,1.261054,NaN,1.342592
3,PESA10055241,BMRI872431,1.340492,1.241811,1.316504,1.210026,0.878811,1.028038,0.899124,1.134547,...,1.115662,1.204035,1.148879,1.305784,1.360100,1.146493,1.306093,1.383056,1.353628,1.281596
4,PESA1006009,BMRI923674,1.380013,1.301129,1.253961,1.023581,0.788452,1.052835,1.093225,1.207636,...,1.124246,1.032560,1.371563,1.362702,1.176671,1.073846,1.334591,1.226049,NaN,1.317092
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1335,PESA9935104,BMRI881199,1.249058,1.236699,1.137976,1.271728,1.131059,1.345062,1.116496,1.045286,...,1.130051,1.091836,1.309259,1.353823,1.118713,1.080458,1.106522,1.133721,0.990150,1.317866
1336,PESA9947716,BMRI447102,1.370706,1.259955,1.189831,1.165071,0.842212,1.206862,0.890192,1.366120,...,1.123191,1.135597,1.058687,1.362250,1.093564,1.004282,1.235063,1.175415,0.661932,1.369928
1337,PESA9954025,BMRI971103,1.285378,1.354978,1.186844,1.003245,1.237914,1.003233,0.946259,1.245459,...,1.080414,1.132013,1.141811,1.316481,1.147023,0.988986,1.231453,1.184928,1.252980,1.246740
1338,PESA996004,IA192427,1.277582,1.259212,1.353739,1.154819,1.005982,1.307102,0.791569,1.269155,...,1.218026,1.198267,1.382225,1.314503,1.343394,1.207571,1.331145,1.289496,0.877926,1.380833
1339,PESA9972964,BMRI105334,1.132287,1.301696,1.195795,1.211182,0.958384,1.301636,0.919924,1.167494,...,1.236339,1.050820,1.121231,1.355665,1.090192,0.934849,1.209012,1.191827,0.638208,1.415698

In [ ]:
repo.cognitive()

,subject_uid,visit_id,age_at_cog_months,age_at_cog_years,cdr_activdomesticas,cdr_activfueradecasa,cdr_cuidadopersonal,cdr_global,cdr_memoria,cdr_orientacion,...,wais_puzles,wais_span_creciente,wais_span_directo,wais_span_inverso,z_compo_attworkmemospeed,z_compo_epismemory,z_compo_globalfull,z_compo_pacc_bbrc,z_compo_pacc_bbrc_plus,z_compo_processingspeed
0,PESA10017225,4,618.766667,51.562842,0.0,0.0,0.0,0.0,0.0,0.0,...,17.0,8.0,6.0,4.0,0.171771,1.128244,0.768365,1.005172,0.729974,-0.074405
1,PESA1002001,4,655.064516,54.586301,0.0,0.0,0.0,0.0,0.0,0.0,...,12.0,8.0,7.0,7.0,3.242329,0.942087,2.176751,2.534507,2.341827,2.363359
2,PESA100489,4,691.5,57.622951,0.0,0.0,0.0,0.0,0.0,0.0,...,17.0,6.0,7.0,5.0,0.340117,1.55591,1.234198,1.15436,1.21868,-0.298993
3,PESA10048900,4,775.290323,64.605479,0.0,0.0,0.0,0.0,0.0,0.0,...,18.0,4.0,5.0,4.0,-2.266308,-0.932193,-1.731374,-1.881857,-1.655297,-1.69753
4,PESA10055241,4,773.0,64.413699,0.5,0.0,1.0,0.5,0.5,0.0,...,6.0,6.0,5.0,4.0,-1.065348,-2.638478,-2.522402,-2.40041,-2.540746,-0.962352
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1373,PESA9935104,4,729.548387,60.794521,0.0,0.0,0.0,0.0,0.0,0.0,...,11.0,7.0,5.0,4.0,-0.294657,-1.795589,-1.474183,-1.187782,-1.365462,0.390962
1374,PESA9947716,4,701.37931,58.446575,0.0,0.0,0.0,0.0,0.0,0.0,...,16.0,6.0,6.0,7.0,1.437316,0.566501,1.056801,0.121655,0.385807,1.191238
1375,PESA9954025,4,624.448276,52.035519,0.0,0.0,0.0,0.0,0.0,0.0,...,21.0,6.0,7.0,4.0,-0.400128,0.466686,0.391403,0.038178,0.47512,0.178901
1376,PESA996004,4,688.387097,57.367123,0.0,0.0,0.0,0.0,0.0,0.0,...,15.0,6.0,7.0,6.0,0.397587,0.109454,0.375277,-0.017019,0.341128,-0.00232
1377,PESA9972964,4,641.433333,53.449315,0.0,0.0,0.0,0.0,0.0,0.0,...,17.0,6.0,6.0,6.0,1.542101,0.905924,1.337689,2.021237,1.860691,1.756291

In [14]:
repo.cognitive(variables=['z_compo_processingspeed', 'z_compo_globalfull', 'z_compo_epismemory', 'z_compo_attworkmemospeed'])

,subject_uid,visit_id,z_compo_attworkmemospeed,z_compo_epismemory,z_compo_globalfull,z_compo_processingspeed
0,PESA10017225,4,0.171771,1.128244,0.768365,-0.074405
1,PESA1002001,4,3.242329,0.942087,2.176751,2.363359
2,PESA100489,4,0.340117,1.555910,1.234198,-0.298993
3,PESA10048900,4,-2.266308,-0.932193,-1.731374,-1.697530
4,PESA10055241,4,-1.065348,-2.638478,-2.522402,-0.962352
...,...,...,...,...,...,...
1373,PESA9935104,4,-0.294657,-1.795589,-1.474183,0.390962
1374,PESA9947716,4,1.437316,0.566501,1.056801,1.191238
1375,PESA9954025,4,-0.400128,0.466686,0.391403,0.178901
1376,PESA996004,4,0.397587,0.109454,0.375277,-0.002320
1377,PESA9972964,4,1.542101,0.905924,1.337689,1.756291