In [1]:
import os
import sys
from pathlib import Path
import pandas as pd
import numpy as np

ROOT = Path(os.path.abspath('')).resolve().parents[2]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))


import nvitk as nv
from nvitk import db

In [2]:
tmp_vascular_att = pd.read_csv('/data_local/LabVF/PESA-Brain/DB/new_vars/Vascular_Atlas_ATT_Results.csv')
tmp_vascular_att

           mri_id                territory  mean_att  median_att  smoothing
0      BMRI817697                 Left_ACA  1.175599    1.184994          0
1      BMRI817697                Right_ACA  1.162422    1.163908          0
2      BMRI817697                 Left_MCA  1.205507    1.211579          0
3      BMRI817697                Right_MCA  1.199488    1.215463          0
4      BMRI817697                 Left_PCA  1.300860    1.296352          0
...           ...                      ...       ...         ...        ...
30289    IA553807             Left_Basilar  1.004291    1.013988          0
30290    IA553807            Right_Basilar  0.997359    1.011045          0
30291    IA553807   Left_Lateral_Ventricle       NaN         NaN          0
30292    IA553807  Right_Lateral_Ventricle       NaN         NaN          0
30293    IA553807                Watershed  1.294408    1.281056          0

[30294 rows x 5 columns]

In [3]:
db_vascular_att = tmp_vascular_att.pivot_table(
    index='mri_id',
    columns=['territory', 'smoothing'],
    values='mean_att',
    aggfunc='mean'
)

# Flatten the MultiIndex columns to match your 'roi-s' format
db_vascular_att.columns = [f"{col[0]}-{col[1]}" for col in db_vascular_att.columns]

# Add patient_id from db_asl_cerebral_perfusion that matches mri_id
db_vascular_att['mri_id'] = pd.Series(pd.NA)
mriid2pesaid = {row['mri_id']: row.name for _, row in db_vascular_att.iterrows()}
db_vascular_att['patient_id'] = db_vascular_att.index.map(mriid2pesaid)
db_vascular_att

,Left_ACA-0,Left_ACA-8,Left_Basilar-0,Left_Basilar-8,Left_MCA-0,Left_MCA-8,Left_PCA-0,Left_PCA-8,Right_ACA-0,Right_ACA-8,Right_Basilar-0,Right_Basilar-8,Right_MCA-0,Right_MCA-8,Right_PCA-0,Right_PCA-8,Watershed-0,Watershed-8,mri_id,patient_id
mri_id,,,,,,,,,,,,,,,,,,,,
BMRI100102,1.321472,1.307595,1.147594,1.191484,1.292698,1.257407,1.279656,1.274163,1.326077,1.306505,1.203652,1.232433,1.342529,1.303386,1.304759,1.294799,1.427158,1.381764,NaN,NaN
BMRI101198,1.215924,1.211927,1.067423,1.127502,1.185932,1.159482,1.193117,1.181748,1.252450,1.237313,1.070519,1.131663,1.200591,1.169922,1.224271,1.213519,1.304880,1.258934,NaN,NaN
BMRI101846,1.218692,1.224967,1.120560,1.146782,1.198390,1.194125,1.251637,1.248673,1.254652,1.251706,1.116226,1.142862,1.226417,1.213873,1.263052,1.256602,1.389370,1.359014,NaN,NaN
BMRI103891,1.196845,1.199444,1.083689,1.056860,1.228141,1.196905,1.199995,1.184765,1.221991,1.215238,1.080799,1.098318,1.235333,1.206449,1.194945,1.186462,1.300105,1.272074,NaN,NaN
BMRI104117,1.247098,1.241798,1.028491,1.081847,1.229464,1.202719,1.207225,1.199603,1.299853,1.275169,1.092258,1.130283,1.264362,1.237684,1.230974,1.218980,1.361692,1.313963,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
IA992381,1.242252,NaN,1.139954,NaN,1.247923,NaN,1.222281,NaN,1.290695,NaN,1.088242,NaN,1.302105,NaN,1.189071,NaN,1.340656,NaN,NaN,NaN
IA992548,1.212339,1.210406,1.143548,1.164324,1.188538,1.173346,1.216447,1.210323,1.204341,1.203485,1.130107,1.139551,1.202342,1.180840,1.205240,1.200708,1.313706,1.292106,NaN,NaN
IA992747,1.296953,NaN,1.214247,NaN,1.274713,NaN,1.289638,NaN,1.267015,NaN,1.142644,NaN,1.283588,NaN,1.276735,NaN,1.397564,NaN,NaN,NaN
IA997088,1.279917,1.279951,1.284146,1.300130,1.290146,1.271367,1.353465,1.348354,1.313286,1.301619,1.218157,1.254569,1.298997,1.274551,1.318106,1.318711,1.419589,1.380779,NaN,NaN
IA997404,1.265064,NaN,1.206381,NaN,1.242816,NaN,1.218763,NaN,1.287085,NaN,1.185890,NaN,1.264677,NaN,1.199641,NaN,1.342318,NaN,NaN,NaN

In [ ]:
# db_vascular_att.to_excel('/data_local/LabVF/PESA-Brain/DB/new_vars/PESABrain_ASLPerfusion_VascularAtlas_MeanATT_20260216.xlsx')

In [5]:
db_vascular_att = tmp_vascular_att.pivot_table(
    index='mri_id',
    columns=['territory', 'smoothing'],
    values='median_att',
    aggfunc='median'
)

# Flatten the MultiIndex columns to match your 'roi-s' format
db_vascular_att.columns = [f"{col[0]}-{col[1]}" for col in db_vascular_att.columns]

# Add patient_id from db_asl_cerebral_perfusion that matches mri_id
db_vascular_att['mri_id'] = pd.Series(pd.NA)
mriid2pesaid = {row['mri_id']: row.name for _, row in db_vascular_att.iterrows()}
db_vascular_att['patient_id'] = db_vascular_att.index.map(mriid2pesaid)
db_vascular_att

,Left_ACA-0,Left_ACA-8,Left_Basilar-0,Left_Basilar-8,Left_MCA-0,Left_MCA-8,Left_PCA-0,Left_PCA-8,Right_ACA-0,Right_ACA-8,Right_Basilar-0,Right_Basilar-8,Right_MCA-0,Right_MCA-8,Right_PCA-0,Right_PCA-8,Watershed-0,Watershed-8,mri_id,patient_id
mri_id,,,,,,,,,,,,,,,,,,,,
BMRI100102,1.320618,1.304485,1.155405,1.204559,1.289383,1.261692,1.288288,1.293783,1.324320,1.300845,1.198657,1.223919,1.352599,1.305578,1.307042,1.292563,1.422639,1.399409,NaN,NaN
BMRI101198,1.217214,1.214515,1.057474,1.126201,1.193130,1.156374,1.193293,1.174466,1.247560,1.231401,1.087819,1.122767,1.204759,1.169674,1.219040,1.204414,1.294516,1.273142,NaN,NaN
BMRI101846,1.216720,1.217262,1.137307,1.140770,1.204991,1.207291,1.248018,1.252304,1.245148,1.251628,1.148124,1.130836,1.233278,1.216742,1.262090,1.241005,1.368309,1.369784,NaN,NaN
BMRI103891,1.193104,1.195030,1.132182,1.090556,1.242842,1.202666,1.219894,1.196181,1.217224,1.210641,1.122147,1.106113,1.248221,1.201974,1.220514,1.206274,1.304047,1.289720,NaN,NaN
BMRI104117,1.244488,1.225780,1.026216,1.081442,1.234448,1.198609,1.212332,1.198573,1.296014,1.270636,1.106659,1.119788,1.266707,1.237823,1.226895,1.217047,1.357703,1.343145,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
IA992381,1.248621,NaN,1.131968,NaN,1.259339,NaN,1.232179,NaN,1.297724,NaN,1.101262,NaN,1.304093,NaN,1.190428,NaN,1.335211,NaN,NaN,NaN
IA992548,1.206971,1.214877,1.148393,1.156410,1.194914,1.173851,1.226133,1.198770,1.202617,1.205893,1.153420,1.145671,1.209533,1.184317,1.215381,1.194907,1.311109,1.296723,NaN,NaN
IA992747,1.307264,NaN,1.231183,NaN,1.280014,NaN,1.294076,NaN,1.277926,NaN,1.166194,NaN,1.288785,NaN,1.286721,NaN,1.389455,NaN,NaN,NaN
IA997088,1.276683,1.290592,1.295861,1.326410,1.293926,1.283052,1.351204,1.354551,1.311172,1.313399,1.220232,1.285357,1.299856,1.288251,1.328270,1.344109,1.410182,1.399787,NaN,NaN
IA997404,1.272574,NaN,1.175525,NaN,1.251863,NaN,1.208451,NaN,1.292581,NaN,1.177011,NaN,1.269067,NaN,1.178379,NaN,1.325550,NaN,NaN,NaN

In [ ]:
# db_vascular_att.to_excel('/data_local/LabVF/PESA-Brain/DB/new_vars/PESABrain_ASLPerfusion_VascularAtlas_MedianATT_20260216.xlsx')